In [1]:
# from waybackpy import WaybackMachineCDXServerAPI
 
# CDN_HOSTS = [
#     "cdn.akamai.steamstatic.com",
#     "cdn.fastly.steamstatic.com",
#     "cdn.cloudflare.steamstatic.com",
#     "steamcdn-a.akamaihd.net",
#     "cdn.steamstatic.com",
#     "cdn2.steamstatic.com",
#     "media.steampowered.com",
# ]
 
# KNOWN_PATH = "/steam/publicstats/contentserver_bandwidth_stacked.jsonp"
 
# seen = set()
# urls = []
 
# for host in CDN_HOSTS:
#     url = f"https://{host}{KNOWN_PATH}"
#     print(f"Querying {host}...", flush=True)
#     try:
#         cdx = WaybackMachineCDXServerAPI(url, match_type="prefix")
#         for snapshot in cdx.snapshots():
#             if snapshot.archive_url not in seen:
#                 seen.add(snapshot.archive_url)
#                 urls.append(snapshot.archive_url)
#     except Exception as e:
#         print(f"  ERROR: {e}")
 
# with open("wayback_urls_all.txt", "w") as f:
#     for url in sorted(urls):
#         f.write(url + "\n")
 
# print(f"\nDone. {len(urls)} URLs written to wayback_urls_all.txt")

In [2]:
with open("jsonp_urls.txt") as f:
    old_urls = set(line.strip() for line in f if line.strip())

In [3]:
with open("wayback_urls_all.txt") as f:
    new_urls = set(line.strip() for line in f if line.strip())

In [4]:
diff = new_urls - old_urls
 
print(f"Old set: {len(old_urls)} URLs")
print(f"New set: {len(new_urls)} URLs")
print(f"New URLs not in old set: {len(diff)}\n")

Old set: 729 URLs
New set: 904 URLs
New URLs not in old set: 888

In [5]:
diff_list = sorted(diff)

In [6]:
import requests
import time
import pandas as pd
from json import loads
from functools import reduce
from fake_useragent import UserAgent
from tqdm import tqdm

SCRAPE_JSONP = True

In [7]:
if SCRAPE_JSONP:
    all_dfs = []

    bad_urls = []
    for url in tqdm(diff_list):
        try:
            ua = UserAgent()
            headers = {"User-Agent": ua.random}
            response = requests.get(url, headers=headers, timeout=300)
        except requests.RequestException as e:
            print(f"Error fetching URL {url}: {e}")
            bad_urls.append(url)
            continue
        startidx = response.text.find("(")
        endidx = response.text.find(")")

        try:
            data = loads(response.text[startidx + 1 : endidx])
        except Exception as e:
            print(f"Error parsing JSONP from URL {url}: {e}")
            continue

        if "json" not in data:
            time.sleep(10)
            continue

        series_list = loads(data["json"])

        df_list = []
        for series in series_list:
            df_dict = {}
            region = series["label"]
            df_dict["Timestamp"] = [
                pd.to_datetime(x[0], unit="ms") for x in series["data"]
            ]
            df_dict[region] = [int(x[1]) for x in series["data"]]
            df_list.append(pd.DataFrame(df_dict))

        df = reduce(
            lambda x, y: pd.merge(x, y, on="Timestamp", how="outer"), df_list
        )
        df = df.sort_values("Timestamp").reset_index(drop=True)
        all_dfs.append(df)
        time.sleep(10)
    
    for url in bad_urls:
        try:
            ua = UserAgent()
            headers = {"User-Agent": ua.random}
            response = requests.get(url, headers=headers, timeout=300)
        except requests.RequestException as e:
            print(f"Error fetching URL {url}: {e}")
            continue
        startidx = response.text.find("(")
        endidx = response.text.find(")")

        try:
            data = loads(response.text[startidx + 1 : endidx])
        except Exception as e:
            print(f"Error parsing JSONP from URL {url}: {e}")
            continue

        if "json" not in data:
            time.sleep(10)
            continue

        series_list = loads(data["json"])

        df_list = []
        for series in series_list:
            df_dict = {}
            region = series["label"]
            df_dict["Timestamp"] = [
                pd.to_datetime(x[0], unit="ms") for x in series["data"]
            ]
            df_dict[region] = [int(x[1]) for x in series["data"]]
            df_list.append(pd.DataFrame(df_dict))

        df = reduce(
            lambda x, y: pd.merge(x, y, on="Timestamp", how="outer"), df_list
        )
        df = df.sort_values("Timestamp").reset_index(drop=True)
        all_dfs.append(df)
        time.sleep(10)

    df_combined = pd.concat(all_dfs, axis=0, ignore_index=True)
    df_combined.to_csv("old_data.csv", index=False)

  0%|          | 0/888 [00:00<?, ?it/s]

  0%|          | 1/888 [00:21<5:12:09, 21.12s/it]

Error fetching URL https://web.archive.org/web/20141229111629/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-24-2014-19: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20141229111629/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-24-2014-19 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027CAB7667B0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  0%|          | 2/888 [00:42<5:12:04, 21.13s/it]

Error fetching URL https://web.archive.org/web/20150107014909/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-31-2014-05: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20150107014909/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-31-2014-05 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027CAB800E10>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  0%|          | 3/888 [01:03<5:11:35, 21.12s/it]

Error fetching URL https://web.archive.org/web/20150115235114/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-07-2015-07: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20150115235114/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-07-2015-07 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027CAB801090>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  0%|          | 4/888 [01:24<5:11:10, 21.12s/it]

Error fetching URL https://web.archive.org/web/20150118054316/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-14-2015-12: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20150118054316/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-14-2015-12 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  1%|          | 5/888 [01:45<5:10:47, 21.12s/it]

Error fetching URL https://web.archive.org/web/20150119034406/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-18-2015-19: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20150119034406/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-18-2015-19 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  1%|          | 6/888 [02:06<5:10:19, 21.11s/it]

Error fetching URL https://web.archive.org/web/20150121142923/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-21-2014-04: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20150121142923/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-21-2014-04 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  1%|          | 7/888 [02:27<5:09:59, 21.11s/it]

Error fetching URL https://web.archive.org/web/20150121161240/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-21-2015-08: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20150121161240/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-21-2015-08 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  1%|          | 8/888 [02:48<5:09:43, 21.12s/it]

Error fetching URL https://web.archive.org/web/20150123141150/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-21-2015-21: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20150123141150/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-21-2015-21 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  1%|          | 9/888 [03:10<5:09:30, 21.13s/it]

Error fetching URL https://web.archive.org/web/20150215162912/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-07-2015-00: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20150215162912/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-07-2015-00 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  1%|          | 10/888 [03:31<5:09:01, 21.12s/it]

Error fetching URL https://web.archive.org/web/20150305185557/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-12-2015-23: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20150305185557/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-12-2015-23 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  1%|          | 11/888 [03:52<5:08:39, 21.12s/it]

Error fetching URL https://web.archive.org/web/20150307180020/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-05-2015-23: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20150307180020/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-05-2015-23 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  1%|▏         | 12/888 [04:13<5:08:21, 21.12s/it]

Error fetching URL https://web.archive.org/web/20150314070032/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-12-2015-12: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20150314070032/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-12-2015-12 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  1%|▏         | 13/888 [04:34<5:07:58, 21.12s/it]

Error fetching URL https://web.archive.org/web/20150323211839/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-21-2015-08: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20150323211839/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-21-2015-08 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  2%|▏         | 14/888 [04:55<5:07:36, 21.12s/it]

Error fetching URL https://web.archive.org/web/20150402223512/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-21-2014-15: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20150402223512/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-21-2014-15 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  2%|▏         | 15/888 [05:16<5:07:18, 21.12s/it]

Error fetching URL https://web.archive.org/web/20150408124632/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-06-2015-00: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20150408124632/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-06-2015-00 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  2%|▏         | 16/888 [05:37<5:07:00, 21.12s/it]

Error fetching URL https://web.archive.org/web/20150412154038/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-10-2015-02: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20150412154038/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-10-2015-02 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  2%|▏         | 17/888 [05:59<5:06:31, 21.12s/it]

Error fetching URL https://web.archive.org/web/20150413230402/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-28-2015-09: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20150413230402/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-28-2015-09 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  2%|▏         | 18/888 [06:20<5:06:06, 21.11s/it]

Error fetching URL https://web.archive.org/web/20150418003814/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-15-2015-13: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20150418003814/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-15-2015-13 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  2%|▏         | 19/888 [06:41<5:05:41, 21.11s/it]

Error fetching URL https://web.archive.org/web/20150422215247/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-19-2015-04: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20150422215247/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-19-2015-04 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  2%|▏         | 20/888 [07:02<5:05:17, 21.10s/it]

Error fetching URL https://web.archive.org/web/20150426173155/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-25-2015-07: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20150426173155/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-25-2015-07 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  2%|▏         | 21/888 [07:23<5:05:08, 21.12s/it]

Error fetching URL https://web.archive.org/web/20150427155655/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-16-2015-07: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20150427155655/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-16-2015-07 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  2%|▏         | 22/888 [07:44<5:04:42, 21.11s/it]

Error fetching URL https://web.archive.org/web/20150506095907/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-01-2015-21: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20150506095907/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-01-2015-21 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  3%|▎         | 23/888 [08:05<5:04:12, 21.10s/it]

Error fetching URL https://web.archive.org/web/20150510003034/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-08-2015-00: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20150510003034/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-08-2015-00 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  3%|▎         | 24/888 [08:26<5:03:50, 21.10s/it]

Error fetching URL https://web.archive.org/web/20150603191247/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-25-2015-23: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20150603191247/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-25-2015-23 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  3%|▎         | 25/888 [08:47<5:03:28, 21.10s/it]

Error fetching URL https://web.archive.org/web/20150603191258/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-17-2015-02: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20150603191258/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-17-2015-02 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  3%|▎         | 26/888 [09:08<5:03:08, 21.10s/it]

Error fetching URL https://web.archive.org/web/20150610234452/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-09-2015-21: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20150610234452/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-09-2015-21 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  3%|▎         | 27/888 [09:30<5:02:58, 21.11s/it]

Error fetching URL https://web.archive.org/web/20150611162132/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-11-2015-09: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20150611162132/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-11-2015-09 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  3%|▎         | 28/888 [09:51<5:02:41, 21.12s/it]

Error fetching URL https://web.archive.org/web/20150704231248/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-03-2015-10: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20150704231248/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-03-2015-10 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  3%|▎         | 29/888 [10:12<5:02:23, 21.12s/it]

Error fetching URL https://web.archive.org/web/20150725072312/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-21-2015-19: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20150725072312/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-21-2015-19 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  3%|▎         | 30/888 [10:33<5:01:52, 21.11s/it]

Error fetching URL https://web.archive.org/web/20150729080351/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-29-2015-01: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20150729080351/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-29-2015-01 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  3%|▎         | 31/888 [10:54<5:01:32, 21.11s/it]

Error fetching URL https://web.archive.org/web/20150805035827/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-22-2015-18: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20150805035827/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-22-2015-18 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  4%|▎         | 32/888 [11:15<5:01:07, 21.11s/it]

Error fetching URL https://web.archive.org/web/20150810021824/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-09-2015-04: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20150810021824/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-09-2015-04 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  4%|▎         | 33/888 [11:36<5:00:40, 21.10s/it]

Error fetching URL https://web.archive.org/web/20150828114406/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-27-2015-05: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20150828114406/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-27-2015-05 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  4%|▍         | 34/888 [11:57<5:00:25, 21.11s/it]

Error fetching URL https://web.archive.org/web/20150905213257/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-04-2015-00: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20150905213257/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-04-2015-00 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  4%|▍         | 35/888 [12:18<5:00:02, 21.10s/it]

Error fetching URL https://web.archive.org/web/20150918023732/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-17-2015-00: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20150918023732/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-17-2015-00 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  4%|▍         | 36/888 [12:40<4:59:43, 21.11s/it]

Error fetching URL https://web.archive.org/web/20151016053618/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-15-2015-22: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20151016053618/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-15-2015-22 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  4%|▍         | 37/888 [13:01<4:59:19, 21.10s/it]

Error fetching URL https://web.archive.org/web/20151021223155/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-19-2015-18: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20151021223155/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-19-2015-18 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  4%|▍         | 38/888 [13:22<4:59:01, 21.11s/it]

Error fetching URL https://web.archive.org/web/20151103161925/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-15-2015-22: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20151103161925/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-15-2015-22 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  4%|▍         | 39/888 [13:43<4:58:42, 21.11s/it]

Error fetching URL https://web.archive.org/web/20151109172353/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-06-2015-10: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20151109172353/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-06-2015-10 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  5%|▍         | 40/888 [14:04<4:58:25, 21.12s/it]

Error fetching URL https://web.archive.org/web/20151126235707/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-21-2015-03: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20151126235707/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-21-2015-03 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  5%|▍         | 41/888 [14:25<4:58:08, 21.12s/it]

Error fetching URL https://web.archive.org/web/20151204093852/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-27-2015-15: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20151204093852/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-27-2015-15 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  5%|▍         | 42/888 [14:46<4:58:24, 21.16s/it]

Error fetching URL https://web.archive.org/web/20151204114037/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-20-2015-16: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20151204114037/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-20-2015-16 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  5%|▍         | 43/888 [15:08<4:57:50, 21.15s/it]

Error fetching URL https://web.archive.org/web/20151204114831/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-15-2015-04: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20151204114831/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-15-2015-04 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  5%|▍         | 44/888 [15:29<4:57:17, 21.13s/it]

Error fetching URL https://web.archive.org/web/20151204114834/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-21-2015-07: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20151204114834/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-21-2015-07 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  5%|▌         | 45/888 [15:50<4:56:45, 21.12s/it]

Error fetching URL https://web.archive.org/web/20151204114837/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-11-2015-16: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20151204114837/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-11-2015-16 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  5%|▌         | 46/888 [16:11<4:56:22, 21.12s/it]

Error fetching URL https://web.archive.org/web/20151204115825/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-14-2015-22: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20151204115825/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-14-2015-22 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  5%|▌         | 47/888 [16:32<4:55:59, 21.12s/it]

Error fetching URL https://web.archive.org/web/20151204120238/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-28-2015-21: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20151204120238/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-28-2015-21 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  5%|▌         | 48/888 [16:53<4:55:38, 21.12s/it]

Error fetching URL https://web.archive.org/web/20151204120601/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-05-2015-05: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20151204120601/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-05-2015-05 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  6%|▌         | 49/888 [17:14<4:55:11, 21.11s/it]

Error fetching URL https://web.archive.org/web/20151204122811/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-16-2015-05: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20151204122811/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-16-2015-05 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  6%|▌         | 50/888 [17:35<4:54:47, 21.11s/it]

Error fetching URL https://web.archive.org/web/20151204124849/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-22-2015-22: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20151204124849/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-22-2015-22 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  6%|▌         | 51/888 [17:56<4:54:23, 21.10s/it]

Error fetching URL https://web.archive.org/web/20151204125403/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-15-2015-03: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20151204125403/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-15-2015-03 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  6%|▌         | 52/888 [18:17<4:54:01, 21.10s/it]

Error fetching URL https://web.archive.org/web/20151204125628/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-25-2015-08: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20151204125628/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-25-2015-08 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  6%|▌         | 53/888 [18:39<4:53:43, 21.11s/it]

Error fetching URL https://web.archive.org/web/20151204125628/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-02-2015-11: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20151204125628/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-02-2015-11 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  6%|▌         | 54/888 [19:00<4:53:19, 21.10s/it]

Error fetching URL https://web.archive.org/web/20151204125640/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-25-2015-14: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20151204125640/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-25-2015-14 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  6%|▌         | 55/888 [19:21<4:53:01, 21.11s/it]

Error fetching URL https://web.archive.org/web/20151204130047/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-11-2015-12: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20151204130047/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-11-2015-12 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  6%|▋         | 56/888 [19:42<4:52:42, 21.11s/it]

Error fetching URL https://web.archive.org/web/20151204131440/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-09-2015-09: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20151204131440/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-09-2015-09 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  6%|▋         | 57/888 [20:03<4:52:22, 21.11s/it]

Error fetching URL https://web.archive.org/web/20151220144328/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-19-2015-00: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20151220144328/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-19-2015-00 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  7%|▋         | 58/888 [20:24<4:52:02, 21.11s/it]

Error fetching URL https://web.archive.org/web/20151225165207/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-11-2015-10: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20151225165207/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-11-2015-10 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  7%|▋         | 59/888 [20:45<4:51:45, 21.12s/it]

Error fetching URL https://web.archive.org/web/20151225165241/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-07-2015-23: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20151225165241/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-07-2015-23 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  7%|▋         | 60/888 [21:06<4:51:24, 21.12s/it]

Error fetching URL https://web.archive.org/web/20151225223548/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-02-2015-17: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20151225223548/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-02-2015-17 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  7%|▋         | 61/888 [21:27<4:51:06, 21.12s/it]

Error fetching URL https://web.archive.org/web/20151226173906/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-11-2015-10: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20151226173906/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-11-2015-10 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  7%|▋         | 62/888 [21:49<4:50:36, 21.11s/it]

Error fetching URL https://web.archive.org/web/20160101223323/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-30-2015-11: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20160101223323/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-30-2015-11 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  7%|▋         | 63/888 [22:10<4:50:11, 21.10s/it]

Error fetching URL https://web.archive.org/web/20160110154126/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-05-2016-10: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20160110154126/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-05-2016-10 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  7%|▋         | 64/888 [22:31<4:49:44, 21.10s/it]

Error fetching URL https://web.archive.org/web/20160118015609/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-18-2016-01: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20160118015609/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-18-2016-01 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  7%|▋         | 65/888 [22:52<4:49:28, 21.10s/it]

Error fetching URL https://web.archive.org/web/20160119222758/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-15-2016-14: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20160119222758/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-15-2016-14 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  7%|▋         | 66/888 [23:13<4:49:12, 21.11s/it]

Error fetching URL https://web.archive.org/web/20160129053507/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-25-2016-10: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20160129053507/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-25-2016-10 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  8%|▊         | 67/888 [23:34<4:48:52, 21.11s/it]

Error fetching URL https://web.archive.org/web/20160208125410/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-03-2016-07: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20160208125410/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-03-2016-07 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  8%|▊         | 68/888 [23:55<4:48:36, 21.12s/it]

Error fetching URL https://web.archive.org/web/20160211193556/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-09-2016-22: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20160211193556/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-09-2016-22 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  8%|▊         | 69/888 [24:16<4:48:18, 21.12s/it]

Error fetching URL https://web.archive.org/web/20160212070647/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-09-2016-22: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20160212070647/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-09-2016-22 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  8%|▊         | 70/888 [24:37<4:47:55, 21.12s/it]

Error fetching URL https://web.archive.org/web/20160212212641/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-09-2016-22: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20160212212641/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-09-2016-22 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  8%|▊         | 71/888 [24:59<4:47:28, 21.11s/it]

Error fetching URL https://web.archive.org/web/20160218144956/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-17-2016-21: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20160218144956/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-17-2016-21 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  8%|▊         | 72/888 [25:20<4:47:16, 21.12s/it]

Error fetching URL https://web.archive.org/web/20160219030630/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-17-2016-21: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20160219030630/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-17-2016-21 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  8%|▊         | 73/888 [25:41<4:46:52, 21.12s/it]

Error fetching URL https://web.archive.org/web/20160228040600/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-24-2016-02: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20160228040600/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-24-2016-02 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  8%|▊         | 74/888 [26:02<4:46:34, 21.12s/it]

Error fetching URL https://web.archive.org/web/20160302153616/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-01-2016-15: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20160302153616/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-01-2016-15 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  8%|▊         | 75/888 [26:23<4:46:11, 21.12s/it]

Error fetching URL https://web.archive.org/web/20160311133931/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-08-2016-13: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20160311133931/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-08-2016-13 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  9%|▊         | 76/888 [26:44<4:45:52, 21.12s/it]

Error fetching URL https://web.archive.org/web/20160316114507/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-15-2016-12: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20160316114507/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-15-2016-12 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  9%|▊         | 77/888 [27:05<4:45:28, 21.12s/it]

Error fetching URL https://web.archive.org/web/20160321031333/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-16-2016-16: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20160321031333/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-16-2016-16 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  9%|▉         | 78/888 [27:26<4:45:05, 21.12s/it]

Error fetching URL https://web.archive.org/web/20160403022154/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-30-2016-04: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20160403022154/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-30-2016-04 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  9%|▉         | 79/888 [27:48<4:44:51, 21.13s/it]

Error fetching URL https://web.archive.org/web/20160408064808/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-06-2016-06: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20160408064808/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-06-2016-06 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  9%|▉         | 80/888 [28:09<4:44:31, 21.13s/it]

Error fetching URL https://web.archive.org/web/20160415122010/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-12-2016-19: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20160415122010/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-12-2016-19 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  9%|▉         | 81/888 [28:30<4:44:01, 21.12s/it]

Error fetching URL https://web.archive.org/web/20160420210154/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-19-2016-15: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20160420210154/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-19-2016-15 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  9%|▉         | 82/888 [28:51<4:43:44, 21.12s/it]

Error fetching URL https://web.archive.org/web/20160429111525/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-25-2016-23: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20160429111525/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-25-2016-23 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  9%|▉         | 83/888 [29:12<4:43:25, 21.12s/it]

Error fetching URL https://web.archive.org/web/20160506061901/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-03-2016-01: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20160506061901/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-03-2016-01 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

  9%|▉         | 84/888 [29:33<4:43:02, 21.12s/it]

Error fetching URL https://web.archive.org/web/20160518091232/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-01-2016-11: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20160518091232/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-01-2016-11 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 10%|▉         | 85/888 [29:54<4:42:35, 21.11s/it]

Error fetching URL https://web.archive.org/web/20160518091339/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-04-2016-07: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20160518091339/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-04-2016-07 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 10%|▉         | 86/888 [30:15<4:42:14, 21.11s/it]

Error fetching URL https://web.archive.org/web/20160520052756/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-17-2016-23: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20160520052756/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-17-2016-23 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 10%|▉         | 87/888 [30:37<4:41:51, 21.11s/it]

Error fetching URL https://web.archive.org/web/20160527054318/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-24-2016-10: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20160527054318/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-24-2016-10 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 10%|▉         | 88/888 [30:58<4:41:39, 21.12s/it]

Error fetching URL https://web.archive.org/web/20160527213202/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-01-2016-23: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20160527213202/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-01-2016-23 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 10%|█         | 89/888 [31:19<4:41:23, 21.13s/it]

Error fetching URL https://web.archive.org/web/20160527213237/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-01-2016-01: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20160527213237/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-01-2016-01 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 10%|█         | 90/888 [31:40<4:40:55, 21.12s/it]

Error fetching URL https://web.archive.org/web/20160527213243/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-09-2015-00: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20160527213243/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-09-2015-00 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 10%|█         | 91/888 [32:01<4:40:31, 21.12s/it]

Error fetching URL https://web.archive.org/web/20160527213243/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-02-2015-11: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20160527213243/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-02-2015-11 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 10%|█         | 92/888 [32:22<4:40:01, 21.11s/it]

Error fetching URL https://web.archive.org/web/20160527213250/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-02-2015-14: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20160527213250/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-02-2015-14 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 10%|█         | 93/888 [32:43<4:39:39, 21.11s/it]

Error fetching URL https://web.archive.org/web/20160527213843/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-27-2016-16: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20160527213843/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-27-2016-16 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 11%|█         | 94/888 [33:04<4:39:26, 21.12s/it]

Error fetching URL https://web.archive.org/web/20160527213944/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-15-2015-18: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20160527213944/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-15-2015-18 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 11%|█         | 95/888 [33:25<4:39:04, 21.12s/it]

Error fetching URL https://web.archive.org/web/20160527214303/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-15-2015-05: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20160527214303/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-15-2015-05 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 11%|█         | 96/888 [33:47<4:38:46, 21.12s/it]

Error fetching URL https://web.archive.org/web/20160527214303/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-18-2015-05: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20160527214303/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-18-2015-05 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 11%|█         | 97/888 [34:08<4:38:24, 21.12s/it]

Error fetching URL https://web.archive.org/web/20160527214402/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-11-2015-19: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20160527214402/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-11-2015-19 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 11%|█         | 98/888 [34:29<4:38:22, 21.14s/it]

Error fetching URL https://web.archive.org/web/20160527214405/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-26-2015-18: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20160527214405/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-26-2015-18 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 11%|█         | 99/888 [34:50<4:37:55, 21.13s/it]

Error fetching URL https://web.archive.org/web/20160527214504/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-09-2015-01: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20160527214504/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-09-2015-01 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 11%|█▏        | 100/888 [35:11<4:37:32, 21.13s/it]

Error fetching URL https://web.archive.org/web/20160527214504/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-15-2015-12: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20160527214504/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-15-2015-12 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 11%|█▏        | 101/888 [35:32<4:37:06, 21.13s/it]

Error fetching URL https://web.archive.org/web/20160528225058/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-01-2015-13: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20160528225058/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-01-2015-13 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 11%|█▏        | 102/888 [35:53<4:36:46, 21.13s/it]

Error fetching URL https://web.archive.org/web/20160607012532/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-05-2016-12: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20160607012532/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-05-2016-12 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 12%|█▏        | 103/888 [36:14<4:36:22, 21.12s/it]

Error fetching URL https://web.archive.org/web/20160612234801/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-11-2016-21: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20160612234801/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-11-2016-21 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 12%|█▏        | 104/888 [36:36<4:36:02, 21.13s/it]

Error fetching URL https://web.archive.org/web/20160620140940/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-18-2016-14: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20160620140940/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-18-2016-14 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 12%|█▏        | 105/888 [36:57<4:35:38, 21.12s/it]

Error fetching URL https://web.archive.org/web/20160627065909/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-26-2016-09: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20160627065909/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-26-2016-09 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 12%|█▏        | 106/888 [37:18<4:35:08, 21.11s/it]

Error fetching URL https://web.archive.org/web/20160705040758/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-02-2016-22: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20160705040758/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-02-2016-22 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 12%|█▏        | 107/888 [37:39<4:34:47, 21.11s/it]

Error fetching URL https://web.archive.org/web/20160711064115/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-08-2016-17: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20160711064115/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-08-2016-17 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 12%|█▏        | 108/888 [38:00<4:34:26, 21.11s/it]

Error fetching URL https://web.archive.org/web/20160716194340/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-14-2016-00: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20160716194340/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-14-2016-00 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 12%|█▏        | 109/888 [38:21<4:34:07, 21.11s/it]

Error fetching URL https://web.archive.org/web/20160719111434/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-26-2016-23: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20160719111434/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-26-2016-23 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 12%|█▏        | 110/888 [38:42<4:33:45, 21.11s/it]

Error fetching URL https://web.archive.org/web/20160722202926/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-19-2016-23: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20160722202926/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-19-2016-23 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 12%|█▎        | 111/888 [39:03<4:33:24, 21.11s/it]

Error fetching URL https://web.archive.org/web/20160725081055/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-23-2016-07: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20160725081055/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-23-2016-07 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 13%|█▎        | 112/888 [39:25<4:33:04, 21.11s/it]

Error fetching URL https://web.archive.org/web/20160726200431/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-24-2016-15: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20160726200431/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-24-2016-15 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 13%|█▎        | 113/888 [39:46<4:32:43, 21.11s/it]

Error fetching URL https://web.archive.org/web/20160811205336/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-09-2016-20: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20160811205336/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-09-2016-20 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 13%|█▎        | 114/888 [40:07<4:32:25, 21.12s/it]

Error fetching URL https://web.archive.org/web/20160820225246/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-15-2016-14: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20160820225246/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-15-2016-14 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 13%|█▎        | 115/888 [40:28<4:32:03, 21.12s/it]

Error fetching URL https://web.archive.org/web/20160826102911/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-24-2016-19: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20160826102911/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-24-2016-19 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 13%|█▎        | 116/888 [40:49<4:31:48, 21.13s/it]

Error fetching URL https://web.archive.org/web/20161005044106/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-01-2016-17: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20161005044106/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-01-2016-17 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 13%|█▎        | 117/888 [41:10<4:31:28, 21.13s/it]

Error fetching URL https://web.archive.org/web/20161010031044/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-08-2016-05: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20161010031044/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-08-2016-05 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 13%|█▎        | 118/888 [41:31<4:31:05, 21.12s/it]

Error fetching URL https://web.archive.org/web/20161030202002/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-30-2016-07: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20161030202002/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-30-2016-07 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 13%|█▎        | 119/888 [41:52<4:30:38, 21.12s/it]

Error fetching URL https://web.archive.org/web/20161119130724/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-19-2016-00: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20161119130724/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-19-2016-00 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 14%|█▎        | 120/888 [42:13<4:30:24, 21.13s/it]

Error fetching URL https://web.archive.org/web/20161207154715/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-15-2015-14: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20161207154715/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-15-2015-14 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 14%|█▎        | 121/888 [42:35<4:30:12, 21.14s/it]

Error fetching URL https://web.archive.org/web/20161208173425/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-10-2016-09: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20161208173425/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-10-2016-09 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 14%|█▎        | 122/888 [42:56<4:29:41, 21.12s/it]

Error fetching URL https://web.archive.org/web/20161213004239/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-13-2016-00: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20161213004239/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-13-2016-00 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 14%|█▍        | 123/888 [43:17<4:29:14, 21.12s/it]

Error fetching URL https://web.archive.org/web/20161224020623/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-24-2016-02: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20161224020623/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-24-2016-02 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 14%|█▍        | 126/888 [43:54<3:00:25, 14.21s/it]

Error parsing JSONP from URL https://web.archive.org/web/20170521100241/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-18-2017-22: Expecting value: line 1 column 1 (char 0)

 14%|█▍        | 127/888 [43:55<2:11:19, 10.35s/it]

Error parsing JSONP from URL https://web.archive.org/web/20170522000838/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-18-2017-22: Expecting value: line 1 column 1 (char 0)

 14%|█▍        | 128/888 [43:56<1:33:28,  7.38s/it]

Error parsing JSONP from URL https://web.archive.org/web/20170522223808/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-21-2017-02: Expecting value: line 1 column 1 (char 0)

 15%|█▍        | 130/888 [44:31<2:43:54, 12.97s/it]

Error fetching URL https://web.archive.org/web/20170613201633/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-07-2017-17: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20170613201633/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-07-2017-17 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 15%|█▍        | 131/888 [44:52<3:14:30, 15.42s/it]

Error fetching URL https://web.archive.org/web/20170627051303/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-25-2017-07: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20170627051303/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-25-2017-07 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 15%|█▍        | 132/888 [45:14<3:35:54, 17.14s/it]

Error fetching URL https://web.archive.org/web/20170706231250/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-02-2017-21: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20170706231250/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-02-2017-21 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 15%|█▍        | 133/888 [45:35<3:50:38, 18.33s/it]

Error fetching URL https://web.archive.org/web/20170728213404/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-27-2017-06: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20170728213404/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-27-2017-06 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 15%|█▌        | 134/888 [45:56<4:00:57, 19.17s/it]

Error fetching URL https://web.archive.org/web/20170803212854/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-02-2017-07: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20170803212854/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-02-2017-07 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 15%|█▌        | 135/888 [46:17<4:07:56, 19.76s/it]

Error fetching URL https://web.archive.org/web/20170817134518/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-15-2017-20: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20170817134518/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-15-2017-20 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 15%|█▌        | 136/888 [46:38<4:12:46, 20.17s/it]

Error fetching URL https://web.archive.org/web/20170831105504/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-26-2017-01: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20170831105504/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-26-2017-01 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 15%|█▌        | 137/888 [46:59<4:15:59, 20.45s/it]

Error fetching URL https://web.archive.org/web/20170901191306/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-31-2017-19: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20170901191306/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-31-2017-19 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 16%|█▌        | 138/888 [47:20<4:18:04, 20.65s/it]

Error fetching URL https://web.archive.org/web/20170908220935/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-07-2017-23: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20170908220935/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-07-2017-23 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 16%|█▌        | 139/888 [47:41<4:19:25, 20.78s/it]

Error fetching URL https://web.archive.org/web/20170910200348/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-09-2017-11: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20170910200348/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-09-2017-11 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 16%|█▌        | 140/888 [48:02<4:20:18, 20.88s/it]

Error fetching URL https://web.archive.org/web/20170917111041/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-16-2017-13: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20170917111041/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-16-2017-13 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 16%|█▌        | 141/888 [48:24<4:20:53, 20.96s/it]

Error fetching URL https://web.archive.org/web/20170918074351/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-18-2017-03: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20170918074351/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-18-2017-03 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 16%|█▌        | 142/888 [48:45<4:21:08, 21.00s/it]

Error fetching URL https://web.archive.org/web/20170921172055/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-28-2017-21: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20170921172055/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-28-2017-21 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 16%|█▌        | 143/888 [49:06<4:21:11, 21.04s/it]

Error fetching URL https://web.archive.org/web/20170921172056/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-26-2017-13: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20170921172056/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-26-2017-13 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 16%|█▌        | 144/888 [49:27<4:21:04, 21.05s/it]

Error fetching URL https://web.archive.org/web/20170921205432/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-14-2016-20: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20170921205432/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-14-2016-20 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 16%|█▋        | 145/888 [49:48<4:20:53, 21.07s/it]

Error fetching URL https://web.archive.org/web/20170928162605/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-27-2017-17: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20170928162605/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-27-2017-17 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 16%|█▋        | 146/888 [50:09<4:20:47, 21.09s/it]

Error fetching URL https://web.archive.org/web/20170929012050/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-25-2016-01: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20170929012050/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-25-2016-01 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 17%|█▋        | 147/888 [50:30<4:20:30, 21.09s/it]

Error fetching URL https://web.archive.org/web/20171013172907/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-02-2016-10: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20171013172907/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-02-2016-10 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 17%|█▋        | 148/888 [50:51<4:20:13, 21.10s/it]

Error fetching URL https://web.archive.org/web/20171013173113/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-27-2016-19: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20171013173113/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-27-2016-19 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 17%|█▋        | 149/888 [51:12<4:19:52, 21.10s/it]

Error fetching URL https://web.archive.org/web/20171013174244/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-23-2015-21: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20171013174244/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-23-2015-21 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 17%|█▋        | 150/888 [51:34<4:19:30, 21.10s/it]

Error fetching URL https://web.archive.org/web/20171101044541/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-30-2017-01: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20171101044541/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-30-2017-01 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 17%|█▋        | 151/888 [51:55<4:19:12, 21.10s/it]

Error fetching URL https://web.archive.org/web/20171111155422/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-10-2017-08: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20171111155422/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-10-2017-08 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 17%|█▋        | 152/888 [52:16<4:18:57, 21.11s/it]

Error fetching URL https://web.archive.org/web/20171113111310/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-10-2017-08: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20171113111310/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-10-2017-08 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 17%|█▋        | 153/888 [52:37<4:18:37, 21.11s/it]

Error fetching URL https://web.archive.org/web/20171123031423/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-20-2017-21: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20171123031423/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-20-2017-21 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 17%|█▋        | 154/888 [52:58<4:18:16, 21.11s/it]

Error fetching URL https://web.archive.org/web/20171128002855/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-26-2017-10: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20171128002855/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-26-2017-10 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 17%|█▋        | 155/888 [53:19<4:17:56, 21.11s/it]

Error fetching URL https://web.archive.org/web/20171207105741/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-05-2017-19: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20171207105741/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-05-2017-19 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 18%|█▊        | 156/888 [53:40<4:17:27, 21.10s/it]

Error fetching URL https://web.archive.org/web/20171212233819/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-11-2017-12: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20171212233819/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-11-2017-12 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 18%|█▊        | 157/888 [54:01<4:17:08, 21.11s/it]

Error fetching URL https://web.archive.org/web/20171216041131/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-14-2017-03: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20171216041131/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-14-2017-03 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 18%|█▊        | 158/888 [54:22<4:16:49, 21.11s/it]

Error fetching URL https://web.archive.org/web/20171220010943/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-09-2017-20: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20171220010943/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-09-2017-20 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 18%|█▊        | 159/888 [54:44<4:16:32, 21.12s/it]

Error fetching URL https://web.archive.org/web/20171221111057/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-26-2016-11: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20171221111057/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-26-2016-11 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 18%|█▊        | 160/888 [55:05<4:16:07, 21.11s/it]

Error fetching URL https://web.archive.org/web/20171223180818/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-22-2017-07: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20171223180818/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-22-2017-07 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 18%|█▊        | 161/888 [55:26<4:15:43, 21.11s/it]

Error fetching URL https://web.archive.org/web/20180114104505/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-13-2017-05: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180114104505/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-13-2017-05 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 18%|█▊        | 162/888 [55:47<4:15:24, 21.11s/it]

Error fetching URL https://web.archive.org/web/20180114104518/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-24-2017-05: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180114104518/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-24-2017-05 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 18%|█▊        | 163/888 [56:08<4:15:04, 21.11s/it]

Error fetching URL https://web.archive.org/web/20180131180157/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-31-2018-18: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180131180157/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-31-2018-18 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 18%|█▊        | 164/888 [56:29<4:14:48, 21.12s/it]

Error fetching URL https://web.archive.org/web/20180211182103/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-06-2017-10: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180211182103/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-06-2017-10 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 19%|█▊        | 165/888 [56:50<4:14:26, 21.12s/it]

Error fetching URL https://web.archive.org/web/20180212175823/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-05-2016-07: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180212175823/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-05-2016-07 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 19%|█▊        | 166/888 [57:11<4:14:01, 21.11s/it]

Error fetching URL https://web.archive.org/web/20180212232259/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-10-2018-08: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180212232259/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-10-2018-08 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 19%|█▉        | 167/888 [57:32<4:13:41, 21.11s/it]

Error fetching URL https://web.archive.org/web/20180216005505/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-25-2016-01: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180216005505/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-25-2016-01 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 19%|█▉        | 168/888 [57:54<4:13:24, 21.12s/it]

Error fetching URL https://web.archive.org/web/20180216020650/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-23-2015-18: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180216020650/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-23-2015-18 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 19%|█▉        | 169/888 [58:15<4:12:58, 21.11s/it]

Error fetching URL https://web.archive.org/web/20180216021340/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-21-2016-12: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180216021340/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-21-2016-12 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 19%|█▉        | 170/888 [58:36<4:12:38, 21.11s/it]

Error fetching URL https://web.archive.org/web/20180216021603/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-24-2016-19: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180216021603/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-24-2016-19 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 19%|█▉        | 171/888 [58:57<4:12:14, 21.11s/it]

Error fetching URL https://web.archive.org/web/20180216021815/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-27-2016-11: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180216021815/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-27-2016-11 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 19%|█▉        | 172/888 [59:18<4:11:50, 21.10s/it]

Error fetching URL https://web.archive.org/web/20180216022450/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-20-2017-10: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180216022450/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-20-2017-10 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 19%|█▉        | 173/888 [59:39<4:11:38, 21.12s/it]

Error fetching URL https://web.archive.org/web/20180216023426/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-15-2017-22: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180216023426/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-15-2017-22 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 20%|█▉        | 174/888 [1:00:00<4:11:16, 21.12s/it]

Error fetching URL https://web.archive.org/web/20180218113536/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-16-2018-09: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180218113536/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-16-2018-09 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 20%|█▉        | 175/888 [1:00:21<4:10:55, 21.12s/it]

Error fetching URL https://web.archive.org/web/20180221201146/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-22-2017-07: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180221201146/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-22-2017-07 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 20%|█▉        | 176/888 [1:00:42<4:10:33, 21.12s/it]

Error fetching URL https://web.archive.org/web/20180221201217/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-13-2017-06: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180221201217/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-13-2017-06 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 20%|█▉        | 177/888 [1:01:04<4:10:16, 21.12s/it]

Error fetching URL https://web.archive.org/web/20180221201502/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-13-2017-02: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180221201502/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-13-2017-02 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 20%|██        | 178/888 [1:01:25<4:09:46, 21.11s/it]

Error fetching URL https://web.archive.org/web/20180221232333/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-21-2017-15: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180221232333/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-21-2017-15 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 20%|██        | 179/888 [1:01:46<4:09:30, 21.11s/it]

Error fetching URL https://web.archive.org/web/20180221232406/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-10-2017-23: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180221232406/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-10-2017-23 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 20%|██        | 180/888 [1:02:07<4:09:08, 21.11s/it]

Error fetching URL https://web.archive.org/web/20180221232438/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-28-2017-18: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180221232438/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-28-2017-18 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 20%|██        | 181/888 [1:02:28<4:08:44, 21.11s/it]

Error fetching URL https://web.archive.org/web/20180221233330/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-18-2017-13: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180221233330/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-18-2017-13 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 20%|██        | 182/888 [1:02:49<4:08:27, 21.12s/it]

Error fetching URL https://web.archive.org/web/20180221233359/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-18-2017-12: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180221233359/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-18-2017-12 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 21%|██        | 183/888 [1:03:10<4:08:06, 21.12s/it]

Error fetching URL https://web.archive.org/web/20180221233459/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-07-2017-04: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180221233459/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-07-2017-04 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 21%|██        | 184/888 [1:03:31<4:07:41, 21.11s/it]

Error fetching URL https://web.archive.org/web/20180221234025/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-23-2016-06: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180221234025/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-23-2016-06 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 21%|██        | 185/888 [1:03:52<4:07:14, 21.10s/it]

Error fetching URL https://web.archive.org/web/20180221234122/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-06-2016-05: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180221234122/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-06-2016-05 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 21%|██        | 186/888 [1:04:14<4:06:58, 21.11s/it]

Error fetching URL https://web.archive.org/web/20180221234153/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-29-2016-01: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180221234153/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-29-2016-01 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 21%|██        | 187/888 [1:04:35<4:06:38, 21.11s/it]

Error fetching URL https://web.archive.org/web/20180221234514/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-27-2016-19: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180221234514/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-27-2016-19 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 21%|██        | 188/888 [1:04:56<4:06:22, 21.12s/it]

Error fetching URL https://web.archive.org/web/20180221234607/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-30-2016-09: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180221234607/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-30-2016-09 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 21%|██▏       | 189/888 [1:05:17<4:06:03, 21.12s/it]

Error fetching URL https://web.archive.org/web/20180221234634/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-26-2016-04: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180221234634/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-26-2016-04 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 21%|██▏       | 190/888 [1:05:38<4:05:40, 21.12s/it]

Error fetching URL https://web.archive.org/web/20180221234835/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-25-2016-04: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180221234835/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-25-2016-04 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 22%|██▏       | 191/888 [1:05:59<4:05:15, 21.11s/it]

Error fetching URL https://web.archive.org/web/20180221235005/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-26-2016-11: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180221235005/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-26-2016-11 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 22%|██▏       | 192/888 [1:06:20<4:05:05, 21.13s/it]

Error fetching URL https://web.archive.org/web/20180221235129/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-21-2016-17: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180221235129/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-21-2016-17 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 22%|██▏       | 193/888 [1:06:41<4:04:40, 21.12s/it]

Error fetching URL https://web.archive.org/web/20180221235245/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-23-2016-04: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180221235245/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-23-2016-04 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 22%|██▏       | 194/888 [1:07:03<4:04:17, 21.12s/it]

Error fetching URL https://web.archive.org/web/20180221235559/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-07-2016-16: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180221235559/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-07-2016-16 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 22%|██▏       | 195/888 [1:07:24<4:03:51, 21.11s/it]

Error fetching URL https://web.archive.org/web/20180221235650/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-18-2016-21: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180221235650/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-18-2016-21 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 22%|██▏       | 196/888 [1:07:45<4:03:33, 21.12s/it]

Error fetching URL https://web.archive.org/web/20180221235927/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-11-2015-23: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180221235927/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-11-2015-23 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 22%|██▏       | 197/888 [1:08:06<4:03:15, 21.12s/it]

Error fetching URL https://web.archive.org/web/20180222000030/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-04-2015-21: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180222000030/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-04-2015-21 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 22%|██▏       | 198/888 [1:08:27<4:02:52, 21.12s/it]

Error fetching URL https://web.archive.org/web/20180222000245/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-16-2015-16: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180222000245/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-16-2015-16 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 22%|██▏       | 199/888 [1:08:48<4:02:30, 21.12s/it]

Error fetching URL https://web.archive.org/web/20180222000436/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-10-2015-11: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180222000436/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-10-2015-11 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 23%|██▎       | 200/888 [1:09:09<4:02:04, 21.11s/it]

Error fetching URL https://web.archive.org/web/20180222000710/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-09-2015-08: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180222000710/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-09-2015-08 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 23%|██▎       | 201/888 [1:09:30<4:01:40, 21.11s/it]

Error fetching URL https://web.archive.org/web/20180222000806/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-17-2015-12: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180222000806/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-17-2015-12 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 23%|██▎       | 202/888 [1:09:51<4:01:17, 21.10s/it]

Error fetching URL https://web.archive.org/web/20180222193812/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-22-2017-02: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180222193812/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-22-2017-02 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 23%|██▎       | 203/888 [1:10:13<4:00:58, 21.11s/it]

Error fetching URL https://web.archive.org/web/20180222194447/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-16-2017-12: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180222194447/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-16-2017-12 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 23%|██▎       | 204/888 [1:10:34<4:00:35, 21.10s/it]

Error fetching URL https://web.archive.org/web/20180222210009/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-31-2017-20: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180222210009/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-31-2017-20 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 23%|██▎       | 205/888 [1:10:55<4:00:12, 21.10s/it]

Error fetching URL https://web.archive.org/web/20180222213428/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-08-2017-06: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180222213428/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-08-2017-06 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 23%|██▎       | 206/888 [1:11:16<3:59:50, 21.10s/it]

Error fetching URL https://web.archive.org/web/20180303171003/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-02-2018-11: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180303171003/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-02-2018-11 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 23%|██▎       | 207/888 [1:11:37<3:59:39, 21.11s/it]

Error fetching URL https://web.archive.org/web/20180304163706/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-01-2016-19: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180304163706/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-01-2016-19 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 23%|██▎       | 208/888 [1:11:58<3:59:14, 21.11s/it]

Error fetching URL https://web.archive.org/web/20180306012653/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-02-2018-20: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180306012653/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-02-2018-20 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 24%|██▎       | 209/888 [1:12:19<3:58:53, 21.11s/it]

Error fetching URL https://web.archive.org/web/20180311235615/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-09-2018-08: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180311235615/http://cdn.akamai.steamstatic.com:80/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-09-2018-08 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 24%|██▎       | 210/888 [1:12:40<3:58:30, 21.11s/it]

Error fetching URL https://web.archive.org/web/20180328151838/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-28-2018-15: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180328151838/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-28-2018-15 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 24%|██▍       | 211/888 [1:13:01<3:58:07, 21.10s/it]

Error fetching URL https://web.archive.org/web/20180419060852/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-21-2018-06: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180419060852/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-21-2018-06 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 24%|██▍       | 212/888 [1:13:23<3:57:54, 21.12s/it]

Error fetching URL https://web.archive.org/web/20180420015807/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-28-2018-06: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180420015807/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-28-2018-06 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 24%|██▍       | 213/888 [1:13:44<3:57:33, 21.12s/it]

Error fetching URL https://web.archive.org/web/20180427115352/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-02-2016-05: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180427115352/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-02-2016-05 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 24%|██▍       | 214/888 [1:14:05<3:57:06, 21.11s/it]

Error fetching URL https://web.archive.org/web/20180427115434/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-16-2018-19: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180427115434/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-16-2018-19 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 24%|██▍       | 215/888 [1:14:26<3:56:45, 21.11s/it]

Error fetching URL https://web.archive.org/web/20180508235655/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-08-2018-23: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180508235655/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-08-2018-23 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 24%|██▍       | 216/888 [1:14:47<3:56:29, 21.11s/it]

Error fetching URL https://web.archive.org/web/20180511013741/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-22-2017-11: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180511013741/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-22-2017-11 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 24%|██▍       | 217/888 [1:15:08<3:56:07, 21.11s/it]

Error fetching URL https://web.archive.org/web/20180511013743/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-25-2017-17: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180511013743/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-25-2017-17 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 25%|██▍       | 218/888 [1:15:29<3:55:46, 21.11s/it]

Error fetching URL https://web.archive.org/web/20180511014133/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-25-2017-13: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180511014133/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-25-2017-13 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 25%|██▍       | 219/888 [1:15:50<3:55:28, 21.12s/it]

Error fetching URL https://web.archive.org/web/20180511014134/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-22-2017-04: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180511014134/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-22-2017-04 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 25%|██▍       | 220/888 [1:16:11<3:55:06, 21.12s/it]

Error fetching URL https://web.archive.org/web/20180511014925/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-18-2018-03: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180511014925/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-18-2018-03 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 25%|██▍       | 221/888 [1:16:33<3:54:37, 21.11s/it]

Error fetching URL https://web.archive.org/web/20180511014927/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-26-2018-02: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180511014927/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-26-2018-02 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 25%|██▌       | 222/888 [1:16:54<3:54:14, 21.10s/it]

Error fetching URL https://web.archive.org/web/20180511014928/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-23-2018-08: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180511014928/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-23-2018-08 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 25%|██▌       | 223/888 [1:17:15<3:53:55, 21.11s/it]

Error fetching URL https://web.archive.org/web/20180511015916/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-27-2017-11: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180511015916/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-27-2017-11 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 25%|██▌       | 224/888 [1:17:36<3:53:36, 21.11s/it]

Error fetching URL https://web.archive.org/web/20180511021011/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-08-2018-09: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180511021011/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-08-2018-09 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 25%|██▌       | 225/888 [1:17:57<3:53:15, 21.11s/it]

Error fetching URL https://web.archive.org/web/20180511021012/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-09-2018-09: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180511021012/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-09-2018-09 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 25%|██▌       | 226/888 [1:18:18<3:52:55, 21.11s/it]

Error fetching URL https://web.archive.org/web/20180518181048/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-01-2018-07: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180518181048/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-01-2018-07 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 26%|██▌       | 227/888 [1:18:39<3:52:34, 21.11s/it]

Error fetching URL https://web.archive.org/web/20180520082614/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-01-2016-19: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180520082614/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-01-2016-19 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 26%|██▌       | 228/888 [1:19:00<3:52:17, 21.12s/it]

Error fetching URL https://web.archive.org/web/20180705150514/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-26-2018-10: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180705150514/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-26-2018-10 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 26%|██▌       | 229/888 [1:19:21<3:51:55, 21.12s/it]

Error fetching URL https://web.archive.org/web/20180713202104/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-24-2018-14: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180713202104/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-24-2018-14 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 26%|██▌       | 230/888 [1:19:43<3:51:28, 21.11s/it]

Error fetching URL https://web.archive.org/web/20180713202210/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-13-2018-21: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180713202210/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-13-2018-21 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 26%|██▌       | 231/888 [1:20:04<3:51:07, 21.11s/it]

Error fetching URL https://web.archive.org/web/20180713202211/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-13-2018-21: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180713202211/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-13-2018-21 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 26%|██▌       | 232/888 [1:20:25<3:50:47, 21.11s/it]

Error fetching URL https://web.archive.org/web/20180718205348/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-16-2017-17: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180718205348/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-16-2017-17 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 26%|██▌       | 233/888 [1:20:46<3:50:27, 21.11s/it]

Error fetching URL https://web.archive.org/web/20180723233053/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-11-2018-06: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180723233053/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-11-2018-06 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 26%|██▋       | 234/888 [1:21:07<3:50:06, 21.11s/it]

Error fetching URL https://web.archive.org/web/20180730220728/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-26-2018-23: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180730220728/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-26-2018-23 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 26%|██▋       | 235/888 [1:21:28<3:49:43, 21.11s/it]

Error fetching URL https://web.archive.org/web/20180809003810/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-02-2018-04: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180809003810/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-02-2018-04 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 27%|██▋       | 236/888 [1:21:49<3:49:23, 21.11s/it]

Error fetching URL https://web.archive.org/web/20180811111522/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-11-2018-11: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180811111522/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-11-2018-11 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 27%|██▋       | 237/888 [1:22:10<3:49:02, 21.11s/it]

Error fetching URL https://web.archive.org/web/20180907062032/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-16-2018-13: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180907062032/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-16-2018-13 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 27%|██▋       | 238/888 [1:22:31<3:48:39, 21.11s/it]

Error fetching URL https://web.archive.org/web/20180909233054/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-23-2018-14: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180909233054/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-23-2018-14 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 27%|██▋       | 239/888 [1:22:53<3:48:19, 21.11s/it]

Error fetching URL https://web.archive.org/web/20180909234102/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-02-2018-07: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20180909234102/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-02-2018-07 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 27%|██▋       | 240/888 [1:23:14<3:48:09, 21.13s/it]

Error fetching URL https://web.archive.org/web/20181031185028/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-02-2018-22: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20181031185028/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-02-2018-22 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 27%|██▋       | 241/888 [1:23:35<3:47:42, 21.12s/it]

Error fetching URL https://web.archive.org/web/20181117194118/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-04-2018-08: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20181117194118/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-04-2018-08 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 27%|██▋       | 242/888 [1:23:56<3:47:20, 21.12s/it]

Error fetching URL https://web.archive.org/web/20181117194324/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-17-2018-19: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20181117194324/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-17-2018-19 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 27%|██▋       | 243/888 [1:24:17<3:46:59, 21.12s/it]

Error fetching URL https://web.archive.org/web/20181204000937/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-04-2018-00: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20181204000937/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-04-2018-00 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 27%|██▋       | 244/888 [1:24:38<3:46:37, 21.11s/it]

Error fetching URL https://web.archive.org/web/20190124230742/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-22-2018-06: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20190124230742/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-22-2018-06 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 28%|██▊       | 245/888 [1:24:59<3:46:13, 21.11s/it]

Error fetching URL https://web.archive.org/web/20190124230816/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-30-2018-07: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20190124230816/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-30-2018-07 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 28%|██▊       | 246/888 [1:25:20<3:45:59, 21.12s/it]

Error fetching URL https://web.archive.org/web/20190124230927/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-27-2018-14: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20190124230927/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-27-2018-14 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 28%|██▊       | 247/888 [1:25:41<3:45:34, 21.11s/it]

Error fetching URL https://web.archive.org/web/20190204205939/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-30-2019-19: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20190204205939/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-30-2019-19 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 28%|██▊       | 248/888 [1:26:03<3:45:09, 21.11s/it]

Error fetching URL https://web.archive.org/web/20190204210013/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-28-2019-06: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20190204210013/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-28-2019-06 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 28%|██▊       | 249/888 [1:26:24<3:44:46, 21.11s/it]

Error fetching URL https://web.archive.org/web/20190204210052/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-22-2019-05: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20190204210052/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-22-2019-05 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 28%|██▊       | 250/888 [1:26:45<3:44:23, 21.10s/it]

Error fetching URL https://web.archive.org/web/20190204210212/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-19-2019-19: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20190204210212/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-19-2019-19 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 28%|██▊       | 251/888 [1:27:06<3:44:14, 21.12s/it]

Error fetching URL https://web.archive.org/web/20190204210237/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-16-2019-00: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20190204210237/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-16-2019-00 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 28%|██▊       | 252/888 [1:27:27<3:43:51, 21.12s/it]

Error fetching URL https://web.archive.org/web/20190304024244/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-10-2015-23: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20190304024244/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-10-2015-23 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 28%|██▊       | 253/888 [1:27:48<3:43:35, 21.13s/it]

Error fetching URL https://web.archive.org/web/20190315172419/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-20-2018-09: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20190315172419/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-20-2018-09 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 29%|██▊       | 254/888 [1:28:09<3:43:12, 21.12s/it]

Error fetching URL https://web.archive.org/web/20190315172514/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-21-2018-00: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20190315172514/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-21-2018-00 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 29%|██▊       | 255/888 [1:28:30<3:42:46, 21.12s/it]

Error fetching URL https://web.archive.org/web/20190321183845/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-16-2019-00: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20190321183845/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-16-2019-00 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 29%|██▉       | 256/888 [1:28:52<3:42:30, 21.12s/it]

Error fetching URL https://web.archive.org/web/20190322145048/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-28-2018-09: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20190322145048/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-28-2018-09 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 29%|██▉       | 257/888 [1:29:13<3:42:10, 21.13s/it]

Error fetching URL https://web.archive.org/web/20190328214617/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-14-2019-15: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20190328214617/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-14-2019-15 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 29%|██▉       | 258/888 [1:29:34<3:41:47, 21.12s/it]

Error fetching URL https://web.archive.org/web/20190328214728/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-21-2018-23: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20190328214728/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-21-2018-23 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 29%|██▉       | 259/888 [1:29:55<3:41:24, 21.12s/it]

Error fetching URL https://web.archive.org/web/20190423135346/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-17-2019-01: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20190423135346/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-17-2019-01 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 29%|██▉       | 260/888 [1:30:16<3:41:02, 21.12s/it]

Error fetching URL https://web.archive.org/web/20190503182305/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-02-2019-19: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20190503182305/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-02-2019-19 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 29%|██▉       | 261/888 [1:30:37<3:40:40, 21.12s/it]

Error fetching URL https://web.archive.org/web/20190503182942/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-02-2019-12: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20190503182942/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-02-2019-12 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 30%|██▉       | 262/888 [1:30:58<3:40:18, 21.12s/it]

Error fetching URL https://web.archive.org/web/20190503185950/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-05-2019-22: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20190503185950/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-05-2019-22 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 30%|██▉       | 263/888 [1:31:19<3:40:00, 21.12s/it]

Error fetching URL https://web.archive.org/web/20190516061049/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-07-2016-06: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20190516061049/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-07-2016-06 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 30%|██▉       | 264/888 [1:31:40<3:39:37, 21.12s/it]

Error fetching URL https://web.archive.org/web/20190520214354/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-20-2019-21: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20190520214354/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-20-2019-21 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 30%|██▉       | 265/888 [1:32:02<3:39:13, 21.11s/it]

Error fetching URL https://web.archive.org/web/20190520214934/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-25-2017-16: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20190520214934/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-25-2017-16 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 30%|██▉       | 266/888 [1:32:23<3:38:49, 21.11s/it]

Error fetching URL https://web.archive.org/web/20190524002602/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-24-2019-00: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20190524002602/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-24-2019-00 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 30%|███       | 267/888 [1:32:44<3:38:28, 21.11s/it]

Error fetching URL https://web.archive.org/web/20190524002617/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-21-2019-17: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20190524002617/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-21-2019-17 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 30%|███       | 268/888 [1:33:05<3:38:08, 21.11s/it]

Error fetching URL https://web.archive.org/web/20190524002641/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-08-2019-00: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20190524002641/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-08-2019-00 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 30%|███       | 269/888 [1:33:26<3:37:54, 21.12s/it]

Error fetching URL https://web.archive.org/web/20190602154725/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-14-2019-01: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20190602154725/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-14-2019-01 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 30%|███       | 270/888 [1:33:47<3:37:34, 21.12s/it]

Error fetching URL https://web.archive.org/web/20190602160733/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-30-2016-10: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20190602160733/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-30-2016-10 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 31%|███       | 271/888 [1:34:08<3:37:14, 21.13s/it]

Error fetching URL https://web.archive.org/web/20190602161226/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-15-2017-06: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20190602161226/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-15-2017-06 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 31%|███       | 272/888 [1:34:29<3:36:48, 21.12s/it]

Error fetching URL https://web.archive.org/web/20190602161333/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-19-2017-02: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20190602161333/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-19-2017-02 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 31%|███       | 273/888 [1:34:51<3:36:26, 21.12s/it]

Error fetching URL https://web.archive.org/web/20190616081339/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-02-2019-19: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20190616081339/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-02-2019-19 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 31%|███       | 274/888 [1:35:12<3:36:05, 21.12s/it]

Error fetching URL https://web.archive.org/web/20190624134107/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-24-2019-13: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20190624134107/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-24-2019-13 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 31%|███       | 275/888 [1:35:33<3:35:43, 21.12s/it]

Error fetching URL https://web.archive.org/web/20190715100955/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-16-2019-06: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20190715100955/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-16-2019-06 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 31%|███       | 276/888 [1:35:54<3:35:22, 21.11s/it]

Error fetching URL https://web.archive.org/web/20190728002440/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-17-2019-01: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20190728002440/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-17-2019-01 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 31%|███       | 277/888 [1:36:15<3:34:58, 21.11s/it]

Error fetching URL https://web.archive.org/web/20190926061638/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-10-2019-02: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20190926061638/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-10-2019-02 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 31%|███▏      | 278/888 [1:36:36<3:34:37, 21.11s/it]

Error fetching URL https://web.archive.org/web/20191018095226/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-14-2019-17: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20191018095226/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-14-2019-17 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 31%|███▏      | 279/888 [1:36:57<3:34:13, 21.11s/it]

Error fetching URL https://web.archive.org/web/20191018095716/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-10-2019-08: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20191018095716/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-10-2019-08 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 32%|███▏      | 280/888 [1:37:18<3:33:54, 21.11s/it]

Error fetching URL https://web.archive.org/web/20191029104929/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-22-2017-15: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20191029104929/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-22-2017-15 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 32%|███▏      | 281/888 [1:37:39<3:33:31, 21.11s/it]

Error fetching URL https://web.archive.org/web/20191029105108/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-15-2017-02: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20191029105108/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-15-2017-02 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 32%|███▏      | 282/888 [1:38:00<3:33:09, 21.10s/it]

Error fetching URL https://web.archive.org/web/20191029105123/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-13-2017-07: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20191029105123/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-13-2017-07 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 32%|███▏      | 283/888 [1:38:22<3:32:46, 21.10s/it]

Error fetching URL https://web.archive.org/web/20191105140951/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-02-2019-01: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20191105140951/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-02-2019-01 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 32%|███▏      | 284/888 [1:38:43<3:32:29, 21.11s/it]

Error fetching URL https://web.archive.org/web/20191106112548/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-21-2019-08: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20191106112548/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-21-2019-08 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 32%|███▏      | 285/888 [1:39:04<3:32:12, 21.12s/it]

Error fetching URL https://web.archive.org/web/20191117034531/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-31-2016-05: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20191117034531/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-31-2016-05 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 32%|███▏      | 286/888 [1:39:25<3:31:51, 21.12s/it]

Error fetching URL https://web.archive.org/web/20191121121530/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-12-2019-01: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20191121121530/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-12-2019-01 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 32%|███▏      | 287/888 [1:39:46<3:31:29, 21.11s/it]

Error fetching URL https://web.archive.org/web/20191121124433/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-28-2019-07: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20191121124433/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-28-2019-07 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 32%|███▏      | 288/888 [1:40:07<3:31:05, 21.11s/it]

Error fetching URL https://web.archive.org/web/20191121124435/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-05-2019-18: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20191121124435/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-05-2019-18 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 33%|███▎      | 289/888 [1:40:28<3:30:42, 21.11s/it]

Error fetching URL https://web.archive.org/web/20191126101508/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-22-2018-07: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20191126101508/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-22-2018-07 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 33%|███▎      | 290/888 [1:40:49<3:30:34, 21.13s/it]

Error fetching URL https://web.archive.org/web/20191201034554/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-01-2019-03: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20191201034554/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-01-2019-03 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 33%|███▎      | 291/888 [1:41:11<3:30:13, 21.13s/it]

Error fetching URL https://web.archive.org/web/20191204061815/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-04-2019-06: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20191204061815/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-04-2019-06 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 33%|███▎      | 292/888 [1:41:32<3:29:47, 21.12s/it]

Error fetching URL https://web.archive.org/web/20191207020642/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-04-2019-06: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20191207020642/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-04-2019-06 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 33%|███▎      | 293/888 [1:41:53<3:29:30, 21.13s/it]

Error fetching URL https://web.archive.org/web/20191210172252/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-28-2018-10: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20191210172252/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-28-2018-10 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 33%|███▎      | 294/888 [1:42:14<3:29:07, 21.12s/it]

Error fetching URL https://web.archive.org/web/20191213001655/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-13-2019-00: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20191213001655/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-13-2019-00 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 33%|███▎      | 295/888 [1:42:35<3:28:53, 21.14s/it]

Error fetching URL https://web.archive.org/web/20191213002732/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-13-2019-00: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20191213002732/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-13-2019-00 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 33%|███▎      | 296/888 [1:42:56<3:28:28, 21.13s/it]

Error fetching URL https://web.archive.org/web/20191227095912/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-27-2019-09: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20191227095912/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-27-2019-09 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 33%|███▎      | 297/888 [1:43:17<3:28:07, 21.13s/it]

Error fetching URL https://web.archive.org/web/20200317210128/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-06-2020-03: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20200317210128/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-06-2020-03 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 34%|███▎      | 298/888 [1:43:38<3:27:43, 21.12s/it]

Error fetching URL https://web.archive.org/web/20200317210139/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-05-2020-12: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20200317210139/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-05-2020-12 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 34%|███▎      | 299/888 [1:44:00<3:27:17, 21.12s/it]

Error fetching URL https://web.archive.org/web/20200320142435/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-18-2020-15: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20200320142435/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-18-2020-15 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 34%|███▍      | 300/888 [1:44:21<3:26:56, 21.12s/it]

Error fetching URL https://web.archive.org/web/20200328003343/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-25-2020-06: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20200328003343/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-25-2020-06 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 34%|███▍      | 301/888 [1:44:42<3:26:34, 21.11s/it]

Error fetching URL https://web.archive.org/web/20200403054052/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-03-2020-05: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20200403054052/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-03-2020-05 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 34%|███▍      | 302/888 [1:45:03<3:26:13, 21.11s/it]

Error fetching URL https://web.archive.org/web/20200407184141/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-02-2020-11: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20200407184141/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-02-2020-11 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 34%|███▍      | 303/888 [1:45:24<3:25:51, 21.11s/it]

Error fetching URL https://web.archive.org/web/20200409171644/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-02-2020-14: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20200409171644/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-02-2020-14 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 34%|███▍      | 304/888 [1:45:45<3:25:30, 21.11s/it]

Error fetching URL https://web.archive.org/web/20200410164149/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-30-2016-13: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20200410164149/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-30-2016-13 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 34%|███▍      | 305/888 [1:46:06<3:25:03, 21.10s/it]

Error fetching URL https://web.archive.org/web/20200425030440/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-25-2020-03: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20200425030440/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-25-2020-03 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 34%|███▍      | 306/888 [1:46:27<3:24:47, 21.11s/it]

Error fetching URL https://web.archive.org/web/20200428164239/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-23-2020-12: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20200428164239/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-23-2020-12 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 35%|███▍      | 307/888 [1:46:48<3:24:26, 21.11s/it]

Error fetching URL https://web.archive.org/web/20200429153436/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-19-2020-16: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20200429153436/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-19-2020-16 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 35%|███▍      | 308/888 [1:47:10<3:24:05, 21.11s/it]

Error fetching URL https://web.archive.org/web/20200501192335/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-30-2019-16: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20200501192335/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-30-2019-16 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 35%|███▍      | 309/888 [1:47:31<3:23:47, 21.12s/it]

Error fetching URL https://web.archive.org/web/20200513052633/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-13-2020-05: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20200513052633/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-13-2020-05 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 35%|███▍      | 310/888 [1:47:52<3:23:28, 21.12s/it]

Error fetching URL https://web.archive.org/web/20200515224657/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-13-2020-05: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20200515224657/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-13-2020-05 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 35%|███▌      | 311/888 [1:48:13<3:23:05, 21.12s/it]

Error fetching URL https://web.archive.org/web/20200517070912/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-17-2020-07: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20200517070912/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-17-2020-07 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 35%|███▌      | 312/888 [1:48:34<3:22:41, 21.11s/it]

Error fetching URL https://web.archive.org/web/20200526142659/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-26-2020-14: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20200526142659/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-26-2020-14 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 35%|███▌      | 313/888 [1:48:55<3:22:28, 21.13s/it]

Error fetching URL https://web.archive.org/web/20200608153330/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-14-2020-14: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20200608153330/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-14-2020-14 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 35%|███▌      | 314/888 [1:49:16<3:22:02, 21.12s/it]

Error fetching URL https://web.archive.org/web/20200615161608/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-09-2020-09: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20200615161608/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-09-2020-09 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 35%|███▌      | 315/888 [1:49:37<3:21:37, 21.11s/it]

Error fetching URL https://web.archive.org/web/20200617132746/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-07-2020-21: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20200617132746/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-07-2020-21 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 36%|███▌      | 316/888 [1:49:58<3:21:16, 21.11s/it]

Error fetching URL https://web.archive.org/web/20200630164452/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-18-2020-07: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20200630164452/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-18-2020-07 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 36%|███▌      | 317/888 [1:50:20<3:20:52, 21.11s/it]

Error fetching URL https://web.archive.org/web/20200817214836/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-22-2020-23: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20200817214836/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-22-2020-23 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 36%|███▌      | 318/888 [1:50:41<3:20:32, 21.11s/it]

Error fetching URL https://web.archive.org/web/20200911031821/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-02-2020-22: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20200911031821/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-02-2020-22 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 36%|███▌      | 319/888 [1:51:02<3:20:12, 21.11s/it]

Error fetching URL https://web.archive.org/web/20200923174615/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-05-2020-00: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20200923174615/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-05-2020-00 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 36%|███▌      | 320/888 [1:51:23<3:19:51, 21.11s/it]

Error fetching URL https://web.archive.org/web/20200923175056/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-19-2020-15: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20200923175056/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-19-2020-15 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 36%|███▌      | 321/888 [1:51:44<3:19:27, 21.11s/it]

Error fetching URL https://web.archive.org/web/20200923175139/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-26-2020-00: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20200923175139/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-26-2020-00 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 36%|███▋      | 322/888 [1:52:05<3:19:05, 21.10s/it]

Error fetching URL https://web.archive.org/web/20200923175359/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-06-2020-11: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20200923175359/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-06-2020-11 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 36%|███▋      | 323/888 [1:52:26<3:18:45, 21.11s/it]

Error fetching URL https://web.archive.org/web/20200923175409/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-09-2020-09: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20200923175409/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-09-2020-09 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 36%|███▋      | 324/888 [1:52:47<3:18:25, 21.11s/it]

Error fetching URL https://web.archive.org/web/20200927104203/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-27-2020-10: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20200927104203/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-27-2020-10 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 37%|███▋      | 325/888 [1:53:08<3:18:10, 21.12s/it]

Error fetching URL https://web.archive.org/web/20200927104236/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-09-2020-09: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20200927104236/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-09-2020-09 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 37%|███▋      | 326/888 [1:53:30<3:17:45, 21.11s/it]

Error fetching URL https://web.archive.org/web/20201018050324/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-08-2020-09: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20201018050324/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-08-2020-09 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 37%|███▋      | 327/888 [1:53:51<3:17:27, 21.12s/it]

Error fetching URL https://web.archive.org/web/20201018050345/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-26-2020-23: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20201018050345/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-26-2020-23 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 37%|███▋      | 328/888 [1:54:12<3:17:05, 21.12s/it]

Error fetching URL https://web.archive.org/web/20201019015855/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-26-2020-23: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20201019015855/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-26-2020-23 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 37%|███▋      | 329/888 [1:54:33<3:16:49, 21.13s/it]

Error fetching URL https://web.archive.org/web/20201020000855/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-26-2020-23: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20201020000855/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-26-2020-23 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 37%|███▋      | 330/888 [1:54:54<3:16:26, 21.12s/it]

Error fetching URL https://web.archive.org/web/20201021053953/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-21-2020-05: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20201021053953/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-21-2020-05 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 37%|███▋      | 331/888 [1:55:15<3:16:00, 21.11s/it]

Error fetching URL https://web.archive.org/web/20201111011524/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-11-2020-01: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20201111011524/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-11-2020-01 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 37%|███▋      | 332/888 [1:55:36<3:15:39, 21.11s/it]

Error fetching URL https://web.archive.org/web/20201121151815/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-18-2020-06: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20201121151815/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-18-2020-06 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 38%|███▊      | 333/888 [1:55:57<3:15:18, 21.11s/it]

Error fetching URL https://web.archive.org/web/20201129065514/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-29-2020-06: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20201129065514/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-29-2020-06 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 38%|███▊      | 334/888 [1:56:19<3:14:52, 21.11s/it]

Error fetching URL https://web.archive.org/web/20201207175338/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-07-2020-17: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20201207175338/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-07-2020-17 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 38%|███▊      | 335/888 [1:56:40<3:14:34, 21.11s/it]

Error fetching URL https://web.archive.org/web/20201208034552/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-02-2020-09: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20201208034552/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-02-2020-09 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 38%|███▊      | 336/888 [1:57:01<3:14:08, 21.10s/it]

Error fetching URL https://web.archive.org/web/20201208040042/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-07-2020-08: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20201208040042/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-07-2020-08 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 38%|███▊      | 337/888 [1:57:22<3:13:49, 21.11s/it]

Error fetching URL https://web.archive.org/web/20201208040640/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-24-2020-15: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20201208040640/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-24-2020-15 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 38%|███▊      | 338/888 [1:57:43<3:13:24, 21.10s/it]

Error fetching URL https://web.archive.org/web/20201208041051/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-08-2020-09: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20201208041051/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-08-2020-09 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 38%|███▊      | 339/888 [1:58:04<3:13:00, 21.09s/it]

Error fetching URL https://web.archive.org/web/20201208041631/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-14-2019-06: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20201208041631/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-14-2019-06 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 38%|███▊      | 340/888 [1:58:25<3:12:47, 21.11s/it]

Error fetching URL https://web.archive.org/web/20201208085626/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-08-2020-08: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20201208085626/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-08-2020-08 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 38%|███▊      | 341/888 [1:58:46<3:12:24, 21.11s/it]

Error fetching URL https://web.archive.org/web/20201208225018/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-08-2020-22: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20201208225018/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-08-2020-22 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 39%|███▊      | 342/888 [1:59:07<3:11:59, 21.10s/it]

Error fetching URL https://web.archive.org/web/20201209145614/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-09-2020-14: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20201209145614/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-09-2020-14 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 39%|███▊      | 343/888 [1:59:28<3:11:38, 21.10s/it]

Error fetching URL https://web.archive.org/web/20201209232909/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-09-2020-23: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20201209232909/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-09-2020-23 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 39%|███▊      | 344/888 [1:59:49<3:11:14, 21.09s/it]

Error fetching URL https://web.archive.org/web/20201209232935/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-09-2020-23: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20201209232935/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-09-2020-23 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 39%|███▉      | 345/888 [2:00:11<3:10:59, 21.10s/it]

Error fetching URL https://web.archive.org/web/20201210001510/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-10-2020-00: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20201210001510/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-10-2020-00 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 39%|███▉      | 346/888 [2:00:32<3:10:42, 21.11s/it]

Error fetching URL https://web.archive.org/web/20201210015408/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-10-2020-01: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20201210015408/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-10-2020-01 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 39%|███▉      | 347/888 [2:00:53<3:10:24, 21.12s/it]

Error fetching URL https://web.archive.org/web/20201210042707/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-10-2020-04: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20201210042707/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-10-2020-04 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 39%|███▉      | 348/888 [2:01:14<3:10:08, 21.13s/it]

Error fetching URL https://web.archive.org/web/20201210110552/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-08-2020-13: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20201210110552/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-08-2020-13 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 39%|███▉      | 349/888 [2:01:35<3:09:45, 21.12s/it]

Error fetching URL https://web.archive.org/web/20201210222130/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-10-2020-22: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20201210222130/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-10-2020-22 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 39%|███▉      | 350/888 [2:01:56<3:09:22, 21.12s/it]

Error fetching URL https://web.archive.org/web/20201211000852/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-11-2020-00: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20201211000852/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-11-2020-00 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 40%|███▉      | 351/888 [2:02:17<3:08:57, 21.11s/it]

Error fetching URL https://web.archive.org/web/20201212092634/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-10-2020-10: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20201212092634/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-10-2020-10 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 40%|███▉      | 352/888 [2:02:38<3:08:41, 21.12s/it]

Error fetching URL https://web.archive.org/web/20201213124353/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-13-2020-12: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20201213124353/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-13-2020-12 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 40%|███▉      | 353/888 [2:03:00<3:08:17, 21.12s/it]

Error fetching URL https://web.archive.org/web/20201215075138/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-15-2020-07: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20201215075138/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-15-2020-07 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 40%|███▉      | 354/888 [2:03:21<3:07:55, 21.12s/it]

Error fetching URL https://web.archive.org/web/20201215081109/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-15-2020-08: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20201215081109/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-15-2020-08 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 40%|███▉      | 355/888 [2:03:42<3:07:36, 21.12s/it]

Error fetching URL https://web.archive.org/web/20201219172623/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-19-2020-17: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20201219172623/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-19-2020-17 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 40%|████      | 356/888 [2:04:03<3:07:12, 21.11s/it]

Error fetching URL https://web.archive.org/web/20201223020333/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-23-2020-02: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20201223020333/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-23-2020-02 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 40%|████      | 357/888 [2:04:24<3:06:50, 21.11s/it]

Error fetching URL https://web.archive.org/web/20201224182122/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-24-2020-18: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20201224182122/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-24-2020-18 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 40%|████      | 358/888 [2:04:45<3:06:30, 21.11s/it]

Error fetching URL https://web.archive.org/web/20201225184539/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-25-2020-18: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20201225184539/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-25-2020-18 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 40%|████      | 359/888 [2:05:06<3:06:09, 21.11s/it]

Error fetching URL https://web.archive.org/web/20201230021142/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-30-2020-02: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20201230021142/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-30-2020-02 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 41%|████      | 360/888 [2:05:27<3:05:45, 21.11s/it]

Error fetching URL https://web.archive.org/web/20210103093841/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-27-2015-09: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20210103093841/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-27-2015-09 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 41%|████      | 361/888 [2:05:48<3:05:24, 21.11s/it]

Error fetching URL https://web.archive.org/web/20210103094648/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-13-2017-19: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20210103094648/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-13-2017-19 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 41%|████      | 362/888 [2:06:10<3:05:04, 21.11s/it]

Error fetching URL https://web.archive.org/web/20210103105000/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-19-2020-15: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20210103105000/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-19-2020-15 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 41%|████      | 363/888 [2:06:31<3:04:41, 21.11s/it]

Error fetching URL https://web.archive.org/web/20210103105609/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-26-2020-23: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20210103105609/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-26-2020-23 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 41%|████      | 364/888 [2:06:52<3:04:21, 21.11s/it]

Error fetching URL https://web.archive.org/web/20210104112332/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-13-2017-02: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20210104112332/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-13-2017-02 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 41%|████      | 365/888 [2:07:13<3:04:00, 21.11s/it]

Error fetching URL https://web.archive.org/web/20210107154333/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-23-2018-00: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20210107154333/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-23-2018-00 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 41%|████      | 366/888 [2:07:34<3:03:40, 21.11s/it]

Error fetching URL https://web.archive.org/web/20210121145727/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-15-2021-11: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20210121145727/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-15-2021-11 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 41%|████▏     | 367/888 [2:07:55<3:03:21, 21.12s/it]

Error fetching URL https://web.archive.org/web/20210212124317/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-12-2021-12: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20210212124317/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-12-2021-12 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 41%|████▏     | 368/888 [2:08:16<3:03:03, 21.12s/it]

Error fetching URL https://web.archive.org/web/20210215181850/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-16-2017-21: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20210215181850/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-16-2017-21 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 42%|████▏     | 369/888 [2:08:37<3:02:45, 21.13s/it]

Error fetching URL https://web.archive.org/web/20210225055000/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-02-2020-09: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20210225055000/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-02-2020-09 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 42%|████▏     | 370/888 [2:08:59<3:02:22, 21.12s/it]

Error fetching URL https://web.archive.org/web/20210301125649/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20210301125649/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 42%|████▏     | 371/888 [2:09:20<3:01:59, 21.12s/it]

Error fetching URL https://web.archive.org/web/20210304161302/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-02-2020-22: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20210304161302/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-02-2020-22 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 42%|████▏     | 372/888 [2:09:41<3:01:32, 21.11s/it]

Error fetching URL https://web.archive.org/web/20210307042215/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-07-2021-04: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20210307042215/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-07-2021-04 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 42%|████▏     | 373/888 [2:10:02<3:01:11, 21.11s/it]

Error fetching URL https://web.archive.org/web/20210307042221/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-19-2021-01: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20210307042221/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-19-2021-01 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 42%|████▏     | 374/888 [2:10:23<3:00:48, 21.11s/it]

Error fetching URL https://web.archive.org/web/20210307042238/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-15-2021-22: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20210307042238/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-15-2021-22 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 42%|████▏     | 375/888 [2:10:44<3:00:28, 21.11s/it]

Error fetching URL https://web.archive.org/web/20210408112249/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-02-2021-17: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20210408112249/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-02-2021-17 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 42%|████▏     | 376/888 [2:11:05<3:00:08, 21.11s/it]

Error fetching URL https://web.archive.org/web/20210615101950/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-14-2021-20: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20210615101950/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-14-2021-20 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 42%|████▏     | 377/888 [2:11:26<2:59:47, 21.11s/it]

Error fetching URL https://web.archive.org/web/20210720175953/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-20-2021-17: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20210720175953/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-20-2021-17 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 43%|████▎     | 378/888 [2:11:47<2:59:32, 21.12s/it]

Error fetching URL https://web.archive.org/web/20210803195913/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-19-2015-23: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20210803195913/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-19-2015-23 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 43%|████▎     | 379/888 [2:12:09<2:59:07, 21.11s/it]

Error fetching URL https://web.archive.org/web/20210904043231/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-02-2021-23: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20210904043231/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-02-2021-23 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 43%|████▎     | 380/888 [2:12:30<2:58:41, 21.10s/it]

Error fetching URL https://web.archive.org/web/20210904043523/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-13-2021-14: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20210904043523/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-13-2021-14 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 43%|████▎     | 381/888 [2:12:51<2:58:23, 21.11s/it]

Error fetching URL https://web.archive.org/web/20210904043810/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-14-2021-22: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20210904043810/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-14-2021-22 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 43%|████▎     | 382/888 [2:13:12<2:58:05, 21.12s/it]

Error fetching URL https://web.archive.org/web/20210904044317/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-15-2021-23: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20210904044317/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-15-2021-23 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 43%|████▎     | 383/888 [2:13:33<2:57:44, 21.12s/it]

Error fetching URL https://web.archive.org/web/20210904195639/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-24-2021-01: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20210904195639/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-24-2021-01 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 43%|████▎     | 384/888 [2:13:54<2:57:22, 21.12s/it]

Error fetching URL https://web.archive.org/web/20210905184059/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-05-2021-18: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20210905184059/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-05-2021-18 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 43%|████▎     | 385/888 [2:14:15<2:57:00, 21.12s/it]

Error fetching URL https://web.archive.org/web/20210922145301/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-22-2021-14: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20210922145301/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-22-2021-14 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 43%|████▎     | 386/888 [2:14:36<2:56:37, 21.11s/it]

Error fetching URL https://web.archive.org/web/20210928160208/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-28-2021-16: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20210928160208/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-28-2021-16 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 44%|████▎     | 387/888 [2:14:57<2:56:16, 21.11s/it]

Error fetching URL https://web.archive.org/web/20211024114822/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-13-2021-10: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20211024114822/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-13-2021-10 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 44%|████▎     | 388/888 [2:15:19<2:55:56, 21.11s/it]

Error fetching URL https://web.archive.org/web/20211115192331/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-04-2021-03: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20211115192331/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-04-2021-03 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 44%|████▍     | 389/888 [2:15:40<2:55:37, 21.12s/it]

Error fetching URL https://web.archive.org/web/20211116071623/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-15-2021-09: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20211116071623/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-15-2021-09 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 44%|████▍     | 390/888 [2:16:01<2:55:13, 21.11s/it]

Error fetching URL https://web.archive.org/web/20211116072736/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-02-2020-19: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20211116072736/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-02-2020-19 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 44%|████▍     | 391/888 [2:16:22<2:54:52, 21.11s/it]

Error fetching URL https://web.archive.org/web/20211116110604/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-04-2021-20: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20211116110604/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-04-2021-20 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 44%|████▍     | 392/888 [2:16:43<2:54:34, 21.12s/it]

Error fetching URL https://web.archive.org/web/20211117040157/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-17-2021-04: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20211117040157/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-17-2021-04 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 44%|████▍     | 393/888 [2:17:04<2:54:10, 21.11s/it]

Error fetching URL https://web.archive.org/web/20211125045705/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-17-2021-18: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20211125045705/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-17-2021-18 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 44%|████▍     | 394/888 [2:17:25<2:53:46, 21.11s/it]

Error fetching URL https://web.archive.org/web/20211125050013/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-24-2021-18: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20211125050013/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-24-2021-18 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 44%|████▍     | 395/888 [2:17:46<2:53:26, 21.11s/it]

Error fetching URL https://web.archive.org/web/20211125072559/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-26-2020-10: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20211125072559/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-26-2020-10 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 45%|████▍     | 396/888 [2:18:07<2:53:06, 21.11s/it]

Error fetching URL https://web.archive.org/web/20211205084340/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-03-2021-07: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20211205084340/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-03-2021-07 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 45%|████▍     | 397/888 [2:18:29<2:52:45, 21.11s/it]

Error fetching URL https://web.archive.org/web/20211206151349/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-28-2020-14: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20211206151349/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-28-2020-14 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 45%|████▍     | 398/888 [2:18:50<2:52:24, 21.11s/it]

Error fetching URL https://web.archive.org/web/20211226121510/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-15-2021-10: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20211226121510/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-15-2021-10 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 45%|████▍     | 399/888 [2:19:11<2:52:04, 21.11s/it]

Error fetching URL https://web.archive.org/web/20211227071810/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-27-2021-07: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20211227071810/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-27-2021-07 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 45%|████▌     | 400/888 [2:19:32<2:51:40, 21.11s/it]

Error fetching URL https://web.archive.org/web/20211227152703/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-08-2021-02: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20211227152703/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-08-2021-02 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 45%|████▌     | 401/888 [2:19:53<2:51:20, 21.11s/it]

Error fetching URL https://web.archive.org/web/20211228113054/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-28-2021-11: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20211228113054/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-28-2021-11 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 45%|████▌     | 402/888 [2:20:14<2:51:02, 21.12s/it]

Error fetching URL https://web.archive.org/web/20211231012534/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-31-2021-01: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20211231012534/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-31-2021-01 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 45%|████▌     | 403/888 [2:20:35<2:50:38, 21.11s/it]

Error fetching URL https://web.archive.org/web/20211231072618/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-31-2021-07: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20211231072618/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-31-2021-07 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 45%|████▌     | 404/888 [2:20:56<2:50:13, 21.10s/it]

Error fetching URL https://web.archive.org/web/20220101141248/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-21-2021-09: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220101141248/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-21-2021-09 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 46%|████▌     | 405/888 [2:21:17<2:49:49, 21.10s/it]

Error fetching URL https://web.archive.org/web/20220102001735/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-08-2021-07: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220102001735/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-08-2021-07 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 46%|████▌     | 406/888 [2:21:39<2:49:30, 21.10s/it]

Error fetching URL https://web.archive.org/web/20220103065257/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-03-2022-06: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220103065257/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-03-2022-06 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 46%|████▌     | 407/888 [2:22:00<2:49:16, 21.11s/it]

Error fetching URL https://web.archive.org/web/20220107042907/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-07-2022-04: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220107042907/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-07-2022-04 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 46%|████▌     | 408/888 [2:22:21<2:48:57, 21.12s/it]

Error fetching URL https://web.archive.org/web/20220111133714/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-11-2022-13: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220111133714/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-11-2022-13 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 46%|████▌     | 409/888 [2:22:42<2:48:32, 21.11s/it]

Error fetching URL https://web.archive.org/web/20220112091632/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-12-2022-09: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220112091632/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-12-2022-09 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 46%|████▌     | 410/888 [2:23:03<2:48:12, 21.11s/it]

Error fetching URL https://web.archive.org/web/20220113052902/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-13-2022-05: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220113052902/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-13-2022-05 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 46%|████▋     | 411/888 [2:23:24<2:47:51, 21.11s/it]

Error fetching URL https://web.archive.org/web/20220114005648/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-18-2021-00: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220114005648/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-18-2021-00 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 46%|████▋     | 412/888 [2:23:45<2:47:29, 21.11s/it]

Error fetching URL https://web.archive.org/web/20220114015646/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-14-2022-01: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220114015646/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-14-2022-01 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 47%|████▋     | 413/888 [2:24:06<2:47:09, 21.11s/it]

Error fetching URL https://web.archive.org/web/20220114095904/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-14-2022-10: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220114095904/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-14-2022-10 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 47%|████▋     | 414/888 [2:24:27<2:46:45, 21.11s/it]

Error fetching URL https://web.archive.org/web/20220115063522/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-15-2022-06: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220115063522/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-15-2022-06 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 47%|████▋     | 415/888 [2:24:49<2:46:22, 21.11s/it]

Error fetching URL https://web.archive.org/web/20220117144531/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-17-2022-14: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220117144531/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-17-2022-14 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 47%|████▋     | 416/888 [2:25:10<2:46:02, 21.11s/it]

Error fetching URL https://web.archive.org/web/20220119132720/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-19-2022-11: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220119132720/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-19-2022-11 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 47%|████▋     | 417/888 [2:25:31<2:45:47, 21.12s/it]

Error fetching URL https://web.archive.org/web/20220119140703/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-19-2022-14: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220119140703/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-19-2022-14 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 47%|████▋     | 418/888 [2:25:52<2:45:25, 21.12s/it]

Error fetching URL https://web.archive.org/web/20220122084027/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-22-2022-08: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220122084027/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-22-2022-08 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 47%|████▋     | 419/888 [2:26:13<2:45:06, 21.12s/it]

Error fetching URL https://web.archive.org/web/20220122103620/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-22-2022-10: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220122103620/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-22-2022-10 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 47%|████▋     | 420/888 [2:26:34<2:44:43, 21.12s/it]

Error fetching URL https://web.archive.org/web/20220123081430/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-23-2022-08: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220123081430/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-23-2022-08 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 47%|████▋     | 421/888 [2:26:55<2:44:21, 21.12s/it]

Error fetching URL https://web.archive.org/web/20220126014916/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-26-2022-01: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220126014916/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-26-2022-01 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 48%|████▊     | 422/888 [2:27:16<2:44:00, 21.12s/it]

Error fetching URL https://web.archive.org/web/20220129145259/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-29-2022-14: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220129145259/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-29-2022-14 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 48%|████▊     | 423/888 [2:27:38<2:43:41, 21.12s/it]

Error fetching URL https://web.archive.org/web/20220130054335/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-30-2022-05: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220130054335/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-30-2022-05 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 48%|████▊     | 424/888 [2:27:59<2:43:21, 21.12s/it]

Error fetching URL https://web.archive.org/web/20220130133804/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-30-2022-13: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220130133804/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-30-2022-13 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 48%|████▊     | 425/888 [2:28:20<2:42:56, 21.12s/it]

Error fetching URL https://web.archive.org/web/20220202092308/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-02-2022-09: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220202092308/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-02-2022-09 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 48%|████▊     | 426/888 [2:28:41<2:42:37, 21.12s/it]

Error fetching URL https://web.archive.org/web/20220204062607/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-04-2022-06: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220204062607/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-04-2022-06 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 48%|████▊     | 427/888 [2:29:02<2:42:16, 21.12s/it]

Error fetching URL https://web.archive.org/web/20220208170653/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-08-2022-17: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220208170653/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-08-2022-17 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 48%|████▊     | 428/888 [2:29:23<2:41:55, 21.12s/it]

Error fetching URL https://web.archive.org/web/20220211120951/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-11-2022-12: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220211120951/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-11-2022-12 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 48%|████▊     | 429/888 [2:29:44<2:41:29, 21.11s/it]

Error fetching URL https://web.archive.org/web/20220211161606/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-11-2022-16: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220211161606/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-11-2022-16 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 48%|████▊     | 430/888 [2:30:05<2:41:08, 21.11s/it]

Error fetching URL https://web.archive.org/web/20220213143448/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-04-2021-03: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220213143448/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-04-2021-03 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 49%|████▊     | 431/888 [2:30:26<2:40:45, 21.11s/it]

Error fetching URL https://web.archive.org/web/20220213143451/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-16-2021-22: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220213143451/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-16-2021-22 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 49%|████▊     | 432/888 [2:30:48<2:40:30, 21.12s/it]

Error fetching URL https://web.archive.org/web/20220213143456/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-17-2021-04: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220213143456/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-17-2021-04 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 49%|████▉     | 433/888 [2:31:09<2:40:08, 21.12s/it]

Error fetching URL https://web.archive.org/web/20220214085242/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-14-2022-08: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220214085242/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-14-2022-08 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 49%|████▉     | 434/888 [2:31:30<2:39:42, 21.11s/it]

Error fetching URL https://web.archive.org/web/20220214105200/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-14-2022-10: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220214105200/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-14-2022-10 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 49%|████▉     | 435/888 [2:31:51<2:39:22, 21.11s/it]

Error fetching URL https://web.archive.org/web/20220218235103/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-17-2021-18: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220218235103/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-17-2021-18 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 49%|████▉     | 436/888 [2:32:12<2:38:59, 21.11s/it]

Error fetching URL https://web.archive.org/web/20220219141126/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-19-2022-14: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220219141126/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-19-2022-14 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 49%|████▉     | 437/888 [2:32:33<2:38:39, 21.11s/it]

Error fetching URL https://web.archive.org/web/20220226021303/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-26-2022-02: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220226021303/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-26-2022-02 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 49%|████▉     | 438/888 [2:32:54<2:38:21, 21.11s/it]

Error fetching URL https://web.archive.org/web/20220226080109/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-26-2022-08: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220226080109/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-26-2022-08 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 49%|████▉     | 439/888 [2:33:15<2:37:58, 21.11s/it]

Error fetching URL https://web.archive.org/web/20220301151904/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-01-2022-15: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220301151904/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-01-2022-15 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 50%|████▉     | 440/888 [2:33:36<2:37:37, 21.11s/it]

Error fetching URL https://web.archive.org/web/20220303023300/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-03-2022-02: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220303023300/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-03-2022-02 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 50%|████▉     | 441/888 [2:33:58<2:37:16, 21.11s/it]

Error fetching URL https://web.archive.org/web/20220303051123/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-03-2022-05: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220303051123/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-03-2022-05 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 50%|████▉     | 442/888 [2:34:19<2:36:53, 21.11s/it]

Error fetching URL https://web.archive.org/web/20220308091519/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-08-2022-09: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220308091519/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-08-2022-09 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 50%|████▉     | 443/888 [2:34:40<2:36:31, 21.10s/it]

Error fetching URL https://web.archive.org/web/20220322081023/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-28-2022-12: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220322081023/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-28-2022-12 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 50%|█████     | 444/888 [2:35:01<2:36:13, 21.11s/it]

Error fetching URL https://web.archive.org/web/20220322151100/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-19-2022-21: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220322151100/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-19-2022-21 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 50%|█████     | 445/888 [2:35:22<2:35:50, 21.11s/it]

Error fetching URL https://web.archive.org/web/20220409233739/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-02-2022-09: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220409233739/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-02-2022-09 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 50%|█████     | 446/888 [2:35:43<2:35:34, 21.12s/it]

Error fetching URL https://web.archive.org/web/20220409233914/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-17-2022-19: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220409233914/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-17-2022-19 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 50%|█████     | 447/888 [2:36:04<2:35:10, 21.11s/it]

Error fetching URL https://web.archive.org/web/20220409234607/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-07-2022-09: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220409234607/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-07-2022-09 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 50%|█████     | 448/888 [2:36:25<2:34:49, 21.11s/it]

Error fetching URL https://web.archive.org/web/20220409235005/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-04-2022-03: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220409235005/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-04-2022-03 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 51%|█████     | 449/888 [2:36:46<2:34:28, 21.11s/it]

Error fetching URL https://web.archive.org/web/20220410154254/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-17-2021-02: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220410154254/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-17-2021-02 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 51%|█████     | 450/888 [2:37:08<2:34:03, 21.10s/it]

Error fetching URL https://web.archive.org/web/20220417133707/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-12-2021-20: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220417133707/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-12-2021-20 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 51%|█████     | 451/888 [2:37:29<2:33:41, 21.10s/it]

Error fetching URL https://web.archive.org/web/20220426055219/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-26-2022-05: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220426055219/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-26-2022-05 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 51%|█████     | 452/888 [2:37:50<2:33:21, 21.11s/it]

Error fetching URL https://web.archive.org/web/20220506125145/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-02-2022-13: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220506125145/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-02-2022-13 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 51%|█████     | 453/888 [2:38:11<2:33:01, 21.11s/it]

Error fetching URL https://web.archive.org/web/20220507054343/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-07-2022-05: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220507054343/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-07-2022-05 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 51%|█████     | 454/888 [2:38:32<2:32:41, 21.11s/it]

Error fetching URL https://web.archive.org/web/20220512202119/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-12-2022-20: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220512202119/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-12-2022-20 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 51%|█████     | 455/888 [2:38:53<2:32:20, 21.11s/it]

Error fetching URL https://web.archive.org/web/20220519230426/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-14-2022-04: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220519230426/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-14-2022-04 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 51%|█████▏    | 456/888 [2:39:14<2:32:00, 21.11s/it]

Error fetching URL https://web.archive.org/web/20220525114317/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-25-2022-11: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220525114317/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-25-2022-11 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 51%|█████▏    | 457/888 [2:39:35<2:31:41, 21.12s/it]

Error fetching URL https://web.archive.org/web/20220613041256/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-13-2022-04: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220613041256/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-13-2022-04 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 52%|█████▏    | 458/888 [2:39:56<2:31:17, 21.11s/it]

Error fetching URL https://web.archive.org/web/20220613042030/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-13-2022-04: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220613042030/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-13-2022-04 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 52%|█████▏    | 459/888 [2:40:18<2:30:57, 21.11s/it]

Error fetching URL https://web.archive.org/web/20220702044420/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-02-2022-04: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220702044420/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-02-2022-04 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 52%|█████▏    | 460/888 [2:40:39<2:30:32, 21.10s/it]

Error fetching URL https://web.archive.org/web/20220801211811/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-21-2022-19: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220801211811/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-21-2022-19 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 52%|█████▏    | 461/888 [2:41:00<2:30:12, 21.11s/it]

Error fetching URL https://web.archive.org/web/20220802195517/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-20-2018-16: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220802195517/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-20-2018-16 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 52%|█████▏    | 462/888 [2:41:21<2:29:52, 21.11s/it]

Error fetching URL https://web.archive.org/web/20220803011525/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-03-2022-06: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220803011525/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-03-2022-06 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 52%|█████▏    | 463/888 [2:41:42<2:29:31, 21.11s/it]

Error fetching URL https://web.archive.org/web/20220805072856/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-05-2022-07: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220805072856/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-05-2022-07 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 52%|█████▏    | 464/888 [2:42:03<2:29:11, 21.11s/it]

Error fetching URL https://web.archive.org/web/20220805210835/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-12-2022-22: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220805210835/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-12-2022-22 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 52%|█████▏    | 465/888 [2:42:24<2:28:50, 21.11s/it]

Error fetching URL https://web.archive.org/web/20220805212738/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-24-2022-22: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220805212738/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-24-2022-22 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 52%|█████▏    | 466/888 [2:42:45<2:28:31, 21.12s/it]

Error fetching URL https://web.archive.org/web/20220805212803/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-19-2022-17: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220805212803/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-19-2022-17 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 53%|█████▎    | 467/888 [2:43:06<2:28:12, 21.12s/it]

Error fetching URL https://web.archive.org/web/20220805213048/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-07-2022-15: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220805213048/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-07-2022-15 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 53%|█████▎    | 468/888 [2:43:28<2:27:52, 21.13s/it]

Error fetching URL https://web.archive.org/web/20220805213312/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-23-2022-00: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220805213312/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-23-2022-00 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 53%|█████▎    | 469/888 [2:43:49<2:27:31, 21.13s/it]

Error fetching URL https://web.archive.org/web/20220805214714/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-13-2021-02: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220805214714/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-13-2021-02 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 53%|█████▎    | 470/888 [2:44:10<2:27:09, 21.12s/it]

Error fetching URL https://web.archive.org/web/20220805220113/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-04-2020-21: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220805220113/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-04-2020-21 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 53%|█████▎    | 471/888 [2:44:31<2:26:46, 21.12s/it]

Error fetching URL https://web.archive.org/web/20220805222617/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-26-2019-14: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220805222617/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-26-2019-14 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 53%|█████▎    | 472/888 [2:44:52<2:26:23, 21.11s/it]

Error fetching URL https://web.archive.org/web/20220805222755/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-13-2019-06: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220805222755/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-13-2019-06 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 53%|█████▎    | 473/888 [2:45:13<2:26:01, 21.11s/it]

Error fetching URL https://web.archive.org/web/20220806173748/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-06-2019-17: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220806173748/https://steamcdn-a.akamaihd.net/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=04-06-2019-17 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 53%|█████▎    | 474/888 [2:45:34<2:25:47, 21.13s/it]

Error fetching URL https://web.archive.org/web/20220806175250/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-02-2018-18: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220806175250/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-02-2018-18 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 53%|█████▎    | 475/888 [2:45:55<2:25:24, 21.12s/it]

Error fetching URL https://web.archive.org/web/20220806175729/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-28-2018-15: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220806175729/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-28-2018-15 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 54%|█████▎    | 476/888 [2:46:17<2:25:01, 21.12s/it]

Error fetching URL https://web.archive.org/web/20220806180820/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-28-2022-07: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220806180820/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=05-28-2022-07 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 54%|█████▎    | 477/888 [2:46:38<2:24:37, 21.11s/it]

Error fetching URL https://web.archive.org/web/20220806181611/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-04-2018-01: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220806181611/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=02-04-2018-01 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 54%|█████▍    | 478/888 [2:46:59<2:24:16, 21.11s/it]

Error fetching URL https://web.archive.org/web/20220904021736/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-04-2022-02: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220904021736/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-04-2022-02 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 54%|█████▍    | 479/888 [2:47:20<2:23:53, 21.11s/it]

Error fetching URL https://web.archive.org/web/20220905122733/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-22-2022-08: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220905122733/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=08-22-2022-08 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 54%|█████▍    | 480/888 [2:47:41<2:23:34, 21.12s/it]

Error fetching URL https://web.archive.org/web/20220911141747/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-11-2022-14: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220911141747/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-11-2022-14 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 54%|█████▍    | 481/888 [2:48:02<2:23:13, 21.11s/it]

Error fetching URL https://web.archive.org/web/20220922224633/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-17-2022-18: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220922224633/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=09-17-2022-18 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 54%|█████▍    | 482/888 [2:48:23<2:22:52, 21.11s/it]

Error fetching URL https://web.archive.org/web/20220927103352/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-02-2022-04: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220927103352/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=07-02-2022-04 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 54%|█████▍    | 483/888 [2:48:44<2:22:35, 21.12s/it]

Error fetching URL https://web.archive.org/web/20221006114406/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-06-2022-11: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20221006114406/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-06-2022-11 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 55%|█████▍    | 484/888 [2:49:05<2:22:13, 21.12s/it]

Error fetching URL https://web.archive.org/web/20221015134237/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-15-2022-00: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20221015134237/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-15-2022-00 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 55%|█████▍    | 485/888 [2:49:27<2:21:56, 21.13s/it]

Error fetching URL https://web.archive.org/web/20221019125237/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-19-2022-12: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20221019125237/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-19-2022-12 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 55%|█████▍    | 486/888 [2:49:48<2:21:33, 21.13s/it]

Error fetching URL https://web.archive.org/web/20221029102525/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-29-2022-10: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20221029102525/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-29-2022-10 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 55%|█████▍    | 487/888 [2:50:09<2:21:10, 21.12s/it]

Error fetching URL https://web.archive.org/web/20221101064429/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-19-2016-05: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20221101064429/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-19-2016-05 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 55%|█████▍    | 488/888 [2:50:30<2:20:46, 21.12s/it]

Error fetching URL https://web.archive.org/web/20221104142840/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-04-2022-14: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20221104142840/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-04-2022-14 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 55%|█████▌    | 489/888 [2:50:51<2:20:24, 21.12s/it]

Error fetching URL https://web.archive.org/web/20221111052627/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-11-2022-05: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20221111052627/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-11-2022-05 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 55%|█████▌    | 490/888 [2:51:12<2:20:03, 21.11s/it]

Error fetching URL https://web.archive.org/web/20221119141607/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-17-2016-13: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20221119141607/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=06-17-2016-13 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 55%|█████▌    | 491/888 [2:51:33<2:19:40, 21.11s/it]

Error fetching URL https://web.archive.org/web/20221121175607/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-07-2017-15: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20221121175607/http://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=10-07-2017-15 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 55%|█████▌    | 492/888 [2:51:54<2:19:23, 21.12s/it]

Error fetching URL https://web.archive.org/web/20221206170529/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-06-2022-17: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20221206170529/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-06-2022-17 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 56%|█████▌    | 493/888 [2:52:16<2:19:01, 21.12s/it]

Error fetching URL https://web.archive.org/web/20221212164015/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-22-2022-12: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20221212164015/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=11-22-2022-12 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C896FBED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 58%|█████▊    | 517/888 [2:57:07<1:30:09, 14.58s/it]

Error fetching URL https://web.archive.org/web/20230712163841/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-29-2023-21: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20230712163841/https://cdn.akamai.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=03-29-2023-21 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

 87%|████████▋ | 776/888 [3:49:06<27:11, 14.57s/it]

Error fetching URL https://web.archive.org/web/20251201054230/https://cdn.fastly.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-01-2025-05: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20251201054230/https://cdn.fastly.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=12-01-2025-05 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027C897F8050>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

100%|██████████| 888/888 [4:10:32<00:00, 16.93s/it]

Error fetching URL https://web.archive.org/web/20220119140703/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-19-2022-14: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20220119140703/https://cdn.cloudflare.steamstatic.com/steam/publicstats/contentserver_bandwidth_stacked.jsonp?v=01-19-2022-14 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027CAB673ED0>, 'Connection to web.archive.org timed out. (connect timeout=300)'))

In [8]:
current_df = pd.read_csv("../data/bandwidths.csv", parse_dates=["Timestamp"])
current_df

,Timestamp,Central America,Africa,Middle East,Oceania,South America,Russia,Asia,Europe,North America
0,2016-10-03 10:20:00,2,5.0,29.0,55.0,31.0,153.0,386.0,465.0,142.0
1,2016-10-03 10:30:00,2,5.0,30.0,53.0,31.0,154.0,391.0,473.0,139.0
2,2016-10-03 10:40:00,2,5.0,31.0,53.0,32.0,154.0,392.0,484.0,134.0
3,2016-10-03 10:50:00,2,5.0,31.0,51.0,32.0,158.0,390.0,498.0,134.0
4,2016-10-03 11:00:00,2,5.0,32.0,51.0,33.0,167.0,402.0,511.0,133.0
...,...,...,...,...,...,...,...,...,...,...
155686,2026-03-13 02:10:00,194,89.0,920.0,495.0,3473.0,607.0,5607.0,2153.0,11721.0
155687,2026-03-13 02:20:00,194,89.0,903.0,497.0,3298.0,607.0,5928.0,2058.0,11555.0
155688,2026-03-13 02:30:00,196,88.0,882.0,522.0,3206.0,594.0,6214.0,1992.0,11491.0
155689,2026-03-13 02:40:00,196,85.0,870.0,522.0,3116.0,594.0,6426.0,1928.0,11338.0
155690,2026-03-13 02:50:00,191,84.0,865.0,528.0,3060.0,605.0,6614.0,1865.0,11094.0

In [9]:
old_df = (
    pd.read_csv("old_data.csv", parse_dates=["Timestamp"])
    .sort_values("Timestamp")
    .reset_index(drop=True)
)
old_df = old_df.loc[
    (old_df["Timestamp"].dt.minute % 10 == 0)
    & (old_df["Timestamp"].dt.second == 0)
]
old_df["nan_count"] = old_df.isnull().sum(axis=1)
old_df = (
    old_df
    .sort_values(by=["Timestamp", "nan_count"])
    .drop_duplicates(subset="Timestamp", keep="first")
    .reset_index(drop=True)
)
old_df = old_df.drop(columns=["nan_count"])

# Filter to values not in current_df
old_df = old_df.loc[~old_df["Timestamp"].isin(current_df["Timestamp"])]
old_df

,Timestamp,Central America,Africa,Middle East,Oceania,South America,Russia,Asia,Europe,North America
109,2019-06-15 03:50:00,10.0,10.0,50.0,146.0,258.0,124.0,1435,315,1373.0
110,2019-06-15 04:00:00,11.0,10.0,49.0,148.0,249.0,125.0,1489,306,1348.0
111,2019-06-15 04:10:00,11.0,10.0,49.0,151.0,244.0,127.0,1532,299,1322.0
112,2019-06-15 04:20:00,11.0,10.0,48.0,148.0,239.0,128.0,1560,299,1309.0
113,2019-06-15 04:30:00,10.0,10.0,48.0,148.0,234.0,134.0,1608,296,1265.0
...,...,...,...,...,...,...,...,...,...,...
36960,2024-05-14 10:10:00,18.0,56.0,414.0,458.0,286.0,1203.0,9422,2999,1499.0
36961,2024-05-14 10:20:00,19.0,59.0,477.0,468.0,322.0,1329.0,9995,3629,1499.0
36962,2024-05-14 10:30:00,19.0,61.0,526.0,471.0,331.0,1389.0,10347,3906,1469.0
36963,2024-05-14 10:40:00,19.0,62.0,559.0,471.0,331.0,1453.0,10877,4117,1395.0
36964,2024-05-14 10:50:00,20.0,66.0,590.0,479.0,351.0,1498.0,11256,4424,1383.0

In [10]:
combined = pd.concat([old_df, current_df], axis=0, ignore_index=True).sort_values("Timestamp").reset_index(drop=True)
regions_all = [
    "Central America",
    "Africa",
    "Middle East",
    "Oceania",
    "South America",
    "Russia",
    "Asia",
    "Europe",
    "North America",
]
combined[regions_all] = combined[regions_all].astype("Int64")
combined.to_csv("../data/bandwidths.csv", index=False)